/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /usr/local/cvs/quickfix/spec/lex.yy.c,v 1.15 2002/06/11 03:14:16 oren Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
static yyconst short int yy_accept[438] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    8,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   21,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    7,    0,    9,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    2,    0,    0,    0,    0,    4,    3,
        0,    0,    0,    0,    0,    5,    0,    0,    0,    8,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    0,    0,

        0,    0,    0,   14,    0,   18,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   10,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    6,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        3,    0,    0,    0,    0,    0,   13,    0,   16,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       17,    0,    0,    0,    0,    0,    0,   11,    0,    0,
        0,    0,    0,    0,    0,   19,    0,    0,    0,   19,

       19,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
        0,    0,    0,    0,    0,   12,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    7,    8,    9,
       10,   11,    8,    8,   12,   13,   14,   15,   15,   16,
       15,   17,   15,   15,   15,   15,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       33,   39,   40,   41,   33,   42,   43,   33,   33,   33,
       44,   44,   44,   44,   44,   44,   45,   46,   46,   47,

       48,   49,   50,   51,   52,   46,   46,   53,   54,   55,
       56,   57,   46,   58,   59,   60,   61,   62,   46,   46,
       63,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    5,    6,    7,
        1,    8,    9,    8,   10,   10,   10,   10,    1,    1,
       11,   12,    1,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   14,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   16
    } ;

static yyconst short int yy_base[455] =
    {   0,
        0,    1,    2,    3,    6,    7,  675,  674,  673,  672,
       10,   11,   14,   15,   18,   25,   19,   20,  694,  699,
       47,  664,   21,  644,   45,   47,   62,  662,  676,  644,
      674,   53,  673,  681,  656,  625,   65,   17,  631,  678,
       16,   66,   75,  623,  639,  642,   68,  657,   76,   83,
       84,   79,   81,  636,  623,  634,  652,  667,   99,  665,
      103,  642,  644,  665,   77,  618,   59,  619,  631,  606,
      619,  604,  638,  625,  646,  645,   94,   97,  111,  637,
      643,  106,  617,  603,  615,  635,  645,  645,  116,  613,
      621,  613,  606,   75,  593,  617,  585,  588,  590,  616,

      599,  105,  119,  600,  118,  120,  118,  131,  615,  590,
      613,  615,  616,  154,  597,  596,  603,  567,  699,  582,
      588,  582,  579,  569,  590,  619,  599,  584,  597,  596,
      595,  585,  579,  592,  591,  590,  145,  156,  580,  574,
      587,  586,  151,  699,  604,  699,  585,  586,  161,  564,
      563,  563,  545,  597,  560,  549,  553,  542,  568,  566,
      573,  557,  571,  699,  570,  551,  553,  567,  699,  699,
       72,  159,  548,  550,  564,  699,  170,   69,  577,    0,
      163,  560,  554,  541,  532,  552,  554,  529,  518,  571,
      551,  549,  558,  530,  556,  555,  545,  526,  552,  148,

      161,  542,  523,  549,  168,  517,  555,    0,  165,  539,
      520,  534,  553,  508,  525,  550,  506,    0,  699,  526,
      519,  527,  520,  516,  524,  517,  150,  154,  522,  515,
      179,  490,  524,  164,  516,  535,  509,  516,  488,  508,
      163,  531,    0,  506,  510,  495,  508,  493,   74,  172,
      492,  190,  467,  507,  175,  503,  502,  496,  519,  470,
      481,  472,  461,  483,  198,  495,  495,  479,  493,  477,
      185,  184,  476,  198,  463,    0,  195,  489,  496,  468,
        0,  452,  485,  458,  456,  452,  699,  494,  482,  454,
      480,  452,  189,  197,  449,  209,  429,    0,  200,  449,

      220,  465,  461,  699,  429,  699,  433,  424,  415,  429,
      440,  445,  438,  443,  202,  204,  438,  217,  441,  209,
      452,    0,  440,  699,  393,  404,  396,  389,  395,  409,
      406,  222,  205,  223,  699,  213,  417,  419,  400,  384,
      377,  385,  372,  359,  376,  375,  388,  224,  237,  220,
      373,  392,  381,  345,  378,  340,  346,  344,  352,  347,
      371,  225,  242,  229,  351,  344,  699,  326,  699,  359,
      331,  331,  352,  350,  233,  246,  237,  340,  346,  307,
      699,  361,  310,  241,  249,  244,  323,  699,  336,  237,
      301,  334,  263,  258,  332,  699,  305,  291,  297,  332,

      331,  339,  297,  296,  281,  313,  289,  282,  328,  303,
      282,  274,  303,  271,  248,  257,  297,  261,  278,  239,
      290,  267,  273,  277,  252,  274,  282,  269,  259,  699,
        0,  256,  261,  233,  117,  699,  699,  308,    1,  322,
      335,  348,    0,  361,  374,  387,  400,  415,  429,  442,
      449,  462,  476,  489
    } ;

static yyconst short int yy_def[455] =
    {   0,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  437,  437,
      437,  437,  439,  437,  437,  437,  440,  441,  437,  437,
      437,  442,  437,  437,  443,  437,  437,  437,  437,  439,
      439,  439,  439,  437,  437,  437,  437,  444,  440,  440,
      440,  441,  441,  437,  437,  437,  445,  437,  442,  446,
      442,  437,  437,  443,  443,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  440,  440,  437,
      437,  441,  437,  437,  437,  437,  446,  437,  442,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,

      437,  437,  437,  437,  440,  440,  437,  441,  437,  437,
      437,  437,  437,  442,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  440,  440,  437,  437,
      437,  437,  441,  437,  437,  437,  437,  437,  442,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      444,  440,  437,  437,  437,  437,  441,  437,  437,  447,
      442,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  444,

      444,  437,  437,  437,  441,  437,  437,  447,  445,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  444,  444,  437,  437,
      441,  437,  437,  445,  437,  437,  437,  437,  437,  437,
      437,  437,  448,  437,  437,  437,  437,  437,  444,  444,
      437,  441,  437,  437,  445,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      444,  444,  437,  441,  437,  449,  445,  437,  450,  437,
      451,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  444,  444,  437,  441,  437,  449,  445,  437,

      450,  452,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  444,  444,  437,  441,  437,  445,
      437,  453,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  444,  444,  441,  437,  445,  437,  453,  437,  437,
      437,  437,  437,  437,  437,  437,  444,  444,  441,  445,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  444,  441,  445,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  444,  441,  445,  437,  437,  437,
      437,  437,  437,  444,  441,  445,  437,  437,  437,  437,
      437,  444,  441,  445,  437,  437,  437,  437,  437,  437,

      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      454,  454,  437,  437,  437,  437,    0,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437
    } ;

static yyconst short int yy_nxt[764] =
    {   0,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,   64,   40,  243,  243,  243,  243,  437,   69,
       21,   21,   22,   22,   23,   23,   25,   25,   26,   26,
       29,   29,   22,   22,   31,   31,   32,   32,   33,   34,
       35,   22,   22,   24,   24,   33,   34,   35,   37,   41,
       37,   30,   30,   36,   36,   42,   57,   67,   45,   58,
       43,   47,   47,   47,   47,   48,   37,   68,   37,   69,
       49,   30,   30,   46,   60,   39,   67,   38,   69,   48,
       92,   61,   47,   47,   47,   47,   48,   48,   75,   80,
       51,   80,   76,   94,   76,   38,   77,   38,  200,   81,

       48,   81,   57,   77,   77,   58,   57,  103,  119,   58,
      206,   78,   94,   70,   48,   38,   80,   77,  104,   57,
       60,   48,   58,   48,   60,  271,   81,  119,   68,  127,
      206,   77,   82,  128,   71,   79,  129,   60,   77,  436,
       77,   80,  130,  131,  139,  132,  140,  133,  171,  141,
      134,   81,  105,  108,   89,  142,  135,   57,  106,   48,
       58,   80,  201,  114,   57,   77,  209,   58,   76,   58,
       76,   81,  138,  205,   76,   60,   77,  137,   80,   77,
       80,   76,   60,  143,   60,   60,   60,  228,   81,   80,
       81,  234,   76,  262,  231,  227,   60,  177,  249,   81,

       80,  250,  172,  263,   76,   76,  149,  181,   80,   76,
       81,  255,  287,  287,  287,  287,   60,   76,   81,   80,
      272,   60,   76,  277,   76,   76,  252,   80,  322,   81,
       60,  347,  302,   80,   60,  294,  315,   81,  274,  293,
      323,   60,   76,   81,   76,   76,  299,   80,  332,  296,
       60,  316,   80,   76,  320,  333,   80,   81,   60,   80,
      336,   76,   81,  318,  348,   60,   81,  397,  334,   81,
      435,  364,  350,   80,  434,  362,  433,  398,  396,   60,
      375,  431,  349,  401,  377,  430,  429,  384,  363,  428,
      427,  386,  426,  381,  425,  424,  423,  376,  369,  392,

      385,  422,  394,  421,  420,  419,  418,  393,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   50,  417,  416,   50,   50,  415,
      414,   50,  413,  412,   50,  411,   50,   52,  410,  409,
      408,  407,   52,  406,  107,  103,  405,   52,  404,   52,
       59,   59,  403,  402,  400,  399,  396,   59,  395,   59,
       59,  391,   59,   48,  390,  389,   48,   48,  388,  387,
       48,   48,  169,   48,  164,   48,   57,  383,  382,  381,
      380,  379,  378,   57,  103,   57,   57,  374,   57,   87,
       87,   87,  373,  372,   87,  371,   87,  370,  369,   87,

      368,   87,  208,  367,  208,  366,  365,  208,  361,  208,
      360,  359,  208,  358,  208,  265,  357,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  298,  356,  298,  355,  354,  298,  353,  298,  352,
      351,  298,  346,  298,  301,  345,  344,  343,  342,  301,
      301,  341,  340,  339,  301,  337,  301,  301,  304,  335,
      176,  304,  304,  304,  302,  169,  331,  164,  330,  302,
      302,  329,  302,  328,  302,  327,  302,  302,  338,  326,
      325,  324,  338,  338,  338,  323,  321,  319,  338,  317,
      338,  432,  314,  313,  312,  311,  432,  432,  310,  309,

      308,  432,  307,  432,  432,  306,  305,  303,  302,  300,
      297,  295,  292,  291,  290,  289,  288,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  276,  275,  273,  270,
      269,  268,  267,  266,  264,  261,  260,  259,  258,  257,
      256,  254,  253,  251,  176,  248,  169,  247,  246,  164,
      245,  244,  242,  241,  240,  239,  238,  237,  236,  235,
      233,  232,  230,  229,  176,  226,  225,  169,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  207,  204,  203,  202,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,

      186,  185,  184,  183,  182,  180,  179,  178,  176,  175,
      174,  173,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  148,  147,  146,  145,  144,  136,  126,
      125,  124,  123,  122,  121,  120,  118,  117,  116,  115,
      113,  437,  112,  111,  110,  109,  107,   81,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   93,   92,   91,
       90,   88,   86,   60,   85,   84,   83,   76,   74,   73,
       72,   69,   68,   66,   65,   63,   62,   56,   55,   54,
       53,   44,   39,  437,   28,   28,   27,   27,   19,  437,

      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437
    } ;

static yyconst short int yy_chk[764] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  443,  439,  218,  218,  218,  218,    0,   41,
        1,    2,    1,    2,    3,    4,    5,    6,    5,    6,
       11,   12,   11,   12,   13,   14,   13,   14,   15,   15,
       15,   17,   18,    3,    4,   16,   16,   16,   21,   23,
       21,   11,   12,   17,   18,   23,   32,   38,   25,   32,
       23,   26,   26,   26,   26,   27,   37,   41,   37,   42,
       27,   11,   12,   25,   32,   26,   38,   21,   43,   49,
       65,   32,   47,   47,   47,   47,   50,   51,   47,   52,
       27,   53,  171,   67,  249,   37,   49,   21,  171,   52,

       78,   53,   59,   50,   51,   59,   61,   77,   94,   61,
      178,   49,   67,   42,   79,   37,   82,   78,   77,   89,
       59,  105,   89,  106,   61,  249,   82,   94,   65,  102,
      178,   79,   53,  102,   43,   51,  102,   89,  105,  435,
      106,  108,  102,  103,  107,  103,  107,  103,  137,  107,
      103,  108,   78,   82,   61,  107,  103,  114,   79,  138,
      114,  143,  172,   89,  149,  137,  181,  149,  200,  181,
      227,  143,  106,  177,  228,  114,  138,  105,  205,  172,
      177,  201,  149,  108,  181,  234,  209,  201,  205,  231,
      177,  209,  250,  241,  205,  200,  255,  143,  227,  231,

      252,  228,  138,  241,  272,  271,  114,  149,  274,  293,
      252,  234,  265,  265,  265,  265,  277,  294,  274,  296,
      250,  299,  315,  255,  316,  333,  231,  318,  301,  296,
      320,  332,  301,  334,  336,  272,  293,  318,  252,  271,
      301,  350,  332,  334,  348,  362,  277,  349,  315,  274,
      364,  294,  363,  375,  299,  316,  376,  349,  377,  385,
      320,  384,  363,  296,  333,  386,  376,  390,  318,  385,
      434,  350,  336,  393,  433,  348,  432,  390,  394,  394,
      362,  429,  334,  393,  364,  428,  427,  375,  349,  426,
      425,  377,  424,  423,  422,  421,  420,  363,  419,  384,

      376,  418,  386,  417,  416,  415,  414,  385,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  440,  413,  412,  440,  440,  411,
      410,  440,  409,  408,  440,  407,  440,  441,  406,  405,
      404,  403,  441,  402,  401,  400,  399,  441,  398,  441,
      442,  442,  397,  395,  392,  391,  389,  442,  387,  442,
      442,  383,  442,  444,  382,  380,  444,  444,  379,  378,
      444,  444,  374,  444,  373,  444,  445,  372,  371,  370,
      368,  366,  365,  445,  361,  445,  445,  360,  445,  446,
      446,  446,  359,  358,  446,  357,  446,  356,  355,  446,

      354,  446,  447,  353,  447,  352,  351,  447,  347,  447,
      346,  345,  447,  344,  447,  448,  343,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  449,  342,  449,  341,  340,  449,  339,  449,  338,
      337,  449,  331,  449,  450,  330,  329,  328,  327,  450,
      450,  326,  325,  323,  450,  321,  450,  450,  451,  319,
      317,  451,  451,  451,  452,  314,  313,  312,  311,  452,
      452,  310,  452,  309,  452,  308,  452,  452,  453,  307,
      305,  303,  453,  453,  453,  302,  300,  297,  453,  295,
      453,  454,  292,  291,  290,  289,  454,  454,  288,  286,

      285,  454,  284,  454,  454,  283,  282,  280,  279,  278,
      275,  273,  270,  269,  268,  267,  266,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  254,  253,  251,  248,
      247,  246,  245,  244,  242,  240,  239,  238,  237,  236,
      235,  233,  232,  230,  229,  226,  225,  224,  223,  222,
      221,  220,  217,  216,  215,  214,  213,  212,  211,  210,
      207,  206,  204,  203,  202,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  179,  175,  174,  173,  168,  167,  166,
      165,  163,  162,  161,  160,  159,  158,  157,  156,  155,

      154,  153,  152,  151,  150,  148,  147,  145,  142,  141,
      140,  139,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  118,
      117,  116,  115,  113,  112,  111,  110,  109,  104,  101,
      100,   99,   98,   97,   96,   95,   93,   92,   91,   90,
       88,   87,   86,   85,   84,   83,   81,   80,   76,   75,
       74,   73,   72,   71,   70,   69,   68,   66,   64,   63,
       62,   60,   58,   57,   56,   55,   54,   48,   46,   45,
       44,   40,   39,   36,   35,   34,   33,   31,   30,   29,
       28,   24,   22,   19,   10,    9,    8,    7,  437,  437,

      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  437,  437,
      437,  437,  437
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "FixLexer.l"
#define INITIAL 0
#line 4 "FixLexer.l"
int ignorePass;
int isFieldStart = 0;
int tabs;
int level = 0;
int lastLevel = 0;
char lastName[128];
char lastNum[5];
char ver[12];
int hasValues = 0;

enum closeTag { fields, message, header, trailer } clTag;
enum messageCat { admin, app } msgCat;

char* condense( char* str, char *removeset )
{
  char *wptr, *rptr;
 
  for(wptr = rptr = str; *rptr != 0; ++rptr, ++wptr)
    if(strchr(removeset,*rptr))
      --wptr;
    else 
      *wptr = *rptr;

  *wptr = 0;
  return str;
}

char* removeDup( char* str, char dup )
{
  char* wptr, *rptr;

  if(strlen(str) <= 1) return str;
  for(wptr = str, rptr = str+1; *rptr != 0; ++rptr, ++wptr)
  {
    if(*rptr == *wptr && *wptr == dup)
      rptr++;
    *wptr = *(rptr - 1);
  }
  *wptr = *(rptr - 1);
  *(wptr+1) = 0;
  return str;
}

char* stripName( char* str, const char* trailer )
{
  char* ptr;
  for(; *str != '>'; ++str) 0;
  ptr = str + 1; 
  while(*ptr != trailer[0] || strncmp(trailer, ptr, strlen(trailer)))
  {
    *(ptr-1)=*ptr;
    ++ptr;
  }
  *(ptr-1) = 0;

  for(str; *str == ' '; ++str) {}
  return condense(str, "\222/ -");
}

char* up( char* str )
{
  char* ptr;
  for(ptr = str; *ptr != 0; ++ptr)
    *ptr = toupper(*ptr);
  return str;
}

char* replace( char* str, char x, char y )
{
  char* ptr;
  for(ptr = str; *ptr != 0; ++ptr)
    if(*ptr == x) *ptr = y;
  return str;
}

char* type( char* str )
{
  static char dayofmonth[11] = "DAYOFMONTH";
  static char monthyear[10] = "MONTHYEAR";
  static char qty[4] = "QTY";

  if(!strcmp("DAY-OF-MONTH", str))
    return dayofmonth;
  else if(!strcmp("MONTH-YEAR", str))
    return monthyear;
  else if(!strcmp("QUANTITY", str))
    return qty;
  else
    return str;
}

char* msg( char* str )
{
  static char ordercancelreplacerequest[26] = "OrderCancelReplaceRequest";
  if(!strcmp("CancelReplaceRequest", str))
    return ordercancelreplacerequest;
  else
    return str;
}

char* value( char* str )
{
  static char unknown[8] = "UNKNOWN";
  static char forexlimit[12] = "FOREX_LIMIT";
  static char forexswap[11] = "FOREX_SWAP";
  static char forexpreviouslyquoted[24] = "FOREX_PREVIOUSLY_QUOTED";
  static char tplus2[7] = "TPLUS2";
  static char tplus3[7] = "TPLUS3";
  static char tplus4[7] = "TPLUS4";
  static char tplus5[7] = "TPLUS5";
  static char fixedpeg[10] = "FIXED_PEG";
  static char shortexemptaffiliated[24] = "SHORT_EXEMPT_AFFILIATED";
  static char shortexemptnotaffiliated[28] = "SHORT_EXEMPT_NOT_AFFILIATED";
  static char shortexemptnonmember[23] = "SHORT_EXEMPT_NONMEMBER";
  static char alreadypending[16] = "ALREADY_PENDING";
  static char duplicateverbal[16] = "DUPLICATE_VERBAL";
  static char yes[4] = "YES";
  static char no[3] = "NO";
  static char snapshotplusupdates[22] = "SNAPSHOT_PLUS_UPDATES";
  static char treasuriesplusagencydebenture[33] = "TREASURIES_PLUS_AGENCY_DEBENTURE";
  static char disableprevious[17] = "DISABLE_PREVIOUS";
  static char noneother[11] = "NONE_OTHER";
  static char fiveyear[7] = "FIVEYR";
  static char tenyear[6] = "TENYR";
  static char thirtyyear[9] = "THIRTYYR";
  static char threemolibor[13] = "THREEMOLIBOR";
  static char sixmolibor[11] = "SIXMOLIBOR";

  if(!strcmp("FOREX__LIMIT", str))
    return forexlimit;
  if(!strcmp("FOREX__SWAP", str))
    return forexswap;
  if(!strcmp("FOREX__PREVIOUSLY_QUOTED", str))
    return forexpreviouslyquoted;
  if(!strcmp("T+2", str))
    return tplus2;
  if(!strcmp("T+3", str))
    return tplus3;
  if(!strcmp("T+4", str))
    return tplus4;
  if(!strcmp("T+_5", str))
    return tplus5;
  if(!strcmp("FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER", str))
    return fixedpeg;
  if(!strcmp("SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKETMAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE", str))
    return shortexemptaffiliated;
  if(!strcmp("SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKETMAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE", str))
    return shortexemptnotaffiliated;
  if(!strcmp("SHORT_EXEMPT_TRANSACTION_FOR_NONMEMBER_COMPETING_MARKETMAKER", str))
    return shortexemptnonmember;
  if(!strcmp("ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS", str))
    return alreadypending;
  if(!strcmp("DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER", str))
    return duplicateverbal;
  if(!strcmp("INDICATES_THAT_PARTY_RECEIVING_MESSAGE_MUST_REPORT_TRADE", str))
    return yes;
  if(!strcmp("INDICATES_THAT_PARTY_SENDING_MESSAGE_WILL_REPORT_TRADE", str))
    return no;
  if(!strcmp("INDICATES_THE_BROKER_IS_RESPONSIBLE_FOR_LOCATING_THE_STOCK", str))
    return yes;
  if(!strcmp("INDICATES_THE_BROKER_IS_NOT_REQUIRED_TO_LOCATE", str))
    return no;
  if(!strcmp("EXECUTE_FOREX_AFTER_SECURITY_TRADE", str))
    return yes;
  if(!strcmp("DO_NOT_EXECUTE_FOREX_AFTER_SECURITY_TRADE", str))
    return no;
  if(!strcmp("SNAPSHOT_+_UPDATES", str))
    return snapshotplusupdates;
  if(!strcmp("TREASURIES_+_AGENCY_DEBENTURE", str))
    return treasuriesplusagencydebenture;
  if(!strcmp("DISABLE_PREVIOUS_SNAPSHOT_+_UPDATE_REQUEST", str))
    return disableprevious;
  if(!strcmp("NONE__OTHER", str))
    return noneother;
  if(!strcmp("5YR", str))  
    return fiveyear;
  if(!strcmp("10YR", str))
    return tenyear;
  if(!strcmp("30YR", str))
    return thirtyyear;
  if(!strcmp("3MOLIBOR", str))
    return threemolibor;
  if(!strcmp("6MOLIBOR", str))
    return sixmolibor;
  if(!strcmp("", str))
    return unknown;
  else
    return str;
}

char* version()
{
  char* ptr = ver;
  ptr += 8;
  return ptr;
}

int alpha( char* str )
{
  char* ptr;
  for(ptr = str; *ptr != 0; ++ptr)
    if(!isalpha(*ptr)) return 0;
  return 1;
}

void printTabs()
{
  int i;
  for( i = 0; i < tabs; ++i )
    printf("   ");
}

int skip( char* str )
{
  if(strcmp("24", str) == 0)
  { 
    printTabs();
    printf("<field number='24' name='IOIOthSvc' type='CHAR'/>\n");
  }

  return !strcmp("101", str) 
     || !strcmp("24", str)
     || !strcmp("51", str);
}

void fieldsStart()
{
  isFieldStart = 1;
  clTag = fields;
  tabs--; printTabs();
  printf("</messages>\n");
  printTabs(); tabs++;
  printf("<fields>\n");
}

void fieldsEnd()
{
  switch(clTag)
  {
  case fields:
    --tabs; printTabs();
    printf("</fields>\n");
    break;
  case header:
    for(; lastLevel > 0; --lastLevel)
    {
      --tabs; printTabs();
      printf("</group>\n");
    } level = 0; lastLevel = 0;

    --tabs; printTabs(); --tabs;
    printf("</header>\n");
    break;
  case trailer:
    --tabs; printTabs(); --tabs;
    printf("</trailer>\n");
    ++tabs; printTabs(); tabs++;
    printf("<messages>\n");
    break;
  case message:
    for(; lastLevel > 0; --lastLevel)
    {
      --tabs; printTabs();
      printf("</group>\n");
    } level = 0; lastLevel = 0;

    --tabs; printTabs();
    printf("</message>\n"); 
    break;
  };
}

#define HTML 1

#define html_fs 2

#define html_fnum 3

#define html_fname 4

#define html_fend 5

#define html_values 6

#define html_msgcat 7

#define html_msgtype 8

#line 972 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 324 "FixLexer.l"


#line 1126 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 438 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 699 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 326 "FixLexer.l"
level++;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 327 "FixLexer.l"
{
  stripName(yytext, "<");
  if(!skip(yytext))
  {
    if(level > lastLevel) 
    {
      printTabs(); tabs++;
      printf("<group number='%s' name='%s'>\n", lastNum, condense(lastName," "));
    }
    else if(level < lastLevel)
    {
      --tabs; printTabs();
      printf("</group>\n");
    }

    printTabs();
    strcpy(lastNum, yytext);
    printf("<field number='%s' ", yytext);
    ignorePass = 0;
    BEGIN(html_fnum);
  }
  else ignorePass = 1;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 351 "FixLexer.l"
BEGIN(html_fname);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 352 "FixLexer.l"
{
  if(!ignorePass)
  {
    condense(stripName(yytext, "<"), " ");
    strcpy(lastName, yytext);
    printf("name='%s' ", condense(yytext, " "));
  }
  BEGIN(html_fname); 
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 362 "FixLexer.l"
{
  static char t[5] = "type";
  static char r[9] = "required";

  if(!ignorePass)
    printf("%s='%s'",
      (clTag == message) || (clTag == header) || (clTag == trailer) ? r : t, 
      type(up(condense(stripName(yytext, "<")," *"))));

  lastLevel = level;
  level = 0;
  BEGIN(html_fend); 
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 376 "FixLexer.l"
{
  if(isFieldStart) BEGIN(html_values);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 379 "FixLexer.l"
printf("/>\n"); BEGIN(html_fs);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 381 "FixLexer.l"
{
  if(strcmp(lastNum,"35"))
  {
    char* val = 0;
    char* str = 0;
    int desc_pos = 0;

    if(++hasValues == 1) printf(">\n");
    tabs++; printTabs();
    while(*(yytext+yyleng-1) == ' ')
      *(yytext+ --yyleng) = 0;
    while(*(yytext) == ' ' || *yytext == '>')
      yytext++;

    val = value(condense(replace(up(yytext),' ', '_'),",/'-"));
    removeDup(val, '_');
    str = (char*)strstr(val, "=&#9;");
    if(str)
      desc_pos = str - val + 5;
    else
      desc_pos = strcspn(val, "=") + 1;
    while(*(val+desc_pos) == '_') ++desc_pos;
 
    if(val && strlen(val+desc_pos) > 0)
    {
      char* i = 0;
      printf("<value enum='");
      for(i = val; *i != '=' && *i != ' ' 
	    && *i != '&' && *i != '_'; ++i)
      {
        printf("%c", *i);
      }
      printf("' description='%s'/>\n", value(val + desc_pos));
    }
    else
      --hasValues;
      
    tabs--;
  }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 421 "FixLexer.l"
{
  if(hasValues)
  {
    printTabs();
    printf("</field>\n");
  }
  else printf("/>\n");

  hasValues = 0;
  BEGIN(html_fs);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 433 "FixLexer.l"
{
  msgCat = app;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 437 "FixLexer.l"
{
  printTabs(); tabs++;
  printf("<message name='%s' ", msg(stripName(yytext, " (")));
  BEGIN(html_msgtype);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 443 "FixLexer.l"
{
  yytext = stripName(yytext+27, "<");
  if(strcmp("ResponsebyMessageType",yytext) == 0)
    BEGIN(HTML);
  else
  {
    printTabs(); tabs++;
    printf("<message name='%s' ", msg(yytext));
    BEGIN(html_msgtype);
  }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 455 "FixLexer.l"
{
  yytext = stripName(yytext, "<");
  if(strcmp("ResponsebyMessageType",yytext) == 0)
    BEGIN(HTML);
  else
  {
    printTabs(); tabs++;
    printf("<message name='%s' ", msg(yytext));
    BEGIN(html_msgtype);
  }
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 467 "FixLexer.l"
{
  printf("msgtype='%c' msgcat='%s'>\n", yytext[10], msgCat == admin ? "admin" : "app");
  BEGIN(html_fs);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 472 "FixLexer.l"
{
  char* verStr;
  strcpy(ver, yytext);
  verStr = (char*)strdup(version());
  verStr[1] = 0;
  printf("<fix major='%s' minor='%s'>\n", verStr, verStr+2);
  free(verStr);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 481 "FixLexer.l"
{
  clTag = header;
  tabs++; printTabs(); tabs++;
  printf("<header>\n");
  BEGIN(html_fs);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 488 "FixLexer.l"
{
  clTag = trailer;
  tabs++; printTabs(); tabs++;
  printf("<trailer>\n");
  BEGIN(html_fs);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 495 "FixLexer.l"
{
  msgCat = admin;
  clTag = message; 
  BEGIN(html_msgcat);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 501 "FixLexer.l"
{
  fieldsStart();
  BEGIN(html_fs);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 506 "FixLexer.l"
{
  switch(clTag)
  {
  case fields: case header: case trailer:
    fieldsEnd();
    BEGIN(HTML);
    break;
  case message:
    fieldsEnd();
    BEGIN(html_msgcat);
  }
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 519 "FixLexer.l"
BEGIN(HTML);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 520 "FixLexer.l"
return 1;
	YY_BREAK
case YY_STATE_EOF(HTML):
case YY_STATE_EOF(html_fs):
case YY_STATE_EOF(html_fnum):
case YY_STATE_EOF(html_fname):
case YY_STATE_EOF(html_fend):
case YY_STATE_EOF(html_values):
case YY_STATE_EOF(html_msgcat):
case YY_STATE_EOF(html_msgtype):
#line 521 "FixLexer.l"
printf("</fix>\n"); return 0;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 523 "FixLexer.l"
ECHO;
	YY_BREAK
#line 1491 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 438 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 438 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 437);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 523 "FixLexer.l"


int main( int argc, char** argv )
{
  FILE* file;
  int ret;

  isFieldStart = 0;

  clTag = fields;
  file = fopen("/dev/null", "w");
  yyout = file;
  ret = yylex();
  close(file);
  return ret;
}
