name: filebot
version: 4.7~snap1
summary: The ultimate TV and Movie Renamer / Subtitle Downloader
description: FileBot is the ultimate tool for renaming your movies, tv shows or anime and even downloading subtitles. It's smart, streamlined for simplicity and just works. Putting the super-efficient UI aside, it's also got a full-featured command-line interface and scripting engine for all sorts of automation. Anything is possible.

confinement: strict

architectures: [amd64]

apps:
  filebot:
    command: bin/filebot
    plugs: [home, network, network-bind, unity7, gsettings, opengl, pulseaudio]

parts:
  filebot:
    plugin: copy
    files:
      filebot.sh: bin/filebot
      FileBot.jar: filebot/FileBot.jar
      lib7-Zip-JBinding.so: filebot/lib/amd64/lib7-Zip-JBinding.so
  oracle-java:
    plugin: copy
    files:
      oracle-java: oracle-java
  packages:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    - fontconfig
    - gtk2-engines-murrine
    - light-themes
    - libcanberra-gtk-module
    - jayatana
    - gvfs
    - unity-gtk2-module
    - overlay-scrollbar-gtk2
    - libmediainfo0v5
    - libchromaprint-tools
    - libgdk-pixbuf2.0-0
    - librsvg2-common
