/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trifort_rootbeer_runtime_CUDAGpuContext */

#ifndef _Included_org_trifort_rootbeer_runtime_CUDAGpuContext
#define _Included_org_trifort_rootbeer_runtime_CUDAGpuContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trifort_rootbeer_runtime_CUDAGpuContext
 * Method:    cudaRun
 * Signature: (IIILorg/trifort/rootbeer/runtime/GpuMemory;Lorg/trifort/rootbeer/runtime/GpuMemory;)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_CUDAContext_cudaRun
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint, jint, jobject, 
   jobject);

#ifdef __cplusplus
}
#endif
#endif
