/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trifort_rootbeer_runtime_FixedMemory */

#ifndef _Included_org_trifort_rootbeer_runtime_FixedMemory
#define _Included_org_trifort_rootbeer_runtime_FixedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadByte
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadByte
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadBoolean
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadBoolean
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadShort
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadShort
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadInt
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteByte
 * Signature: (JBJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteByte
  (JNIEnv *, jobject, jlong, jbyte, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteBoolean
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteBoolean
  (JNIEnv *, jobject, jlong, jboolean, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteShort
 * Signature: (JSJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteShort
  (JNIEnv *, jobject, jlong, jshort, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteInt
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteInt
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteFloat
 * Signature: (JFJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteFloat
  (JNIEnv *, jobject, jlong, jfloat, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteDouble
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteDouble
  (JNIEnv *, jobject, jlong, jdouble, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteIntArray
  (JNIEnv *, jobject, jintArray, jlong, jint, jint);

JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteIntArrayEx
  (JNIEnv *, jobject, jintArray, jlong, jint, jint);


JNIEXPORT jlong JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_malloc
  (JNIEnv *env, jobject this_obj, jlong size);

JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_free
  (JNIEnv *env, jobject this_obj, jlong address);

#ifdef __cplusplus
}
#endif
#endif
