#!/bin/bash
ROOT=.
FROM=${ROOT}/
TO=${ROOT}/corelib/
MV=/bin/mv
CP=/bin/cp

$CP ${FROM}BlowFish.cpp $TO
$CP ${FROM}BlowFish.h $TO
$CP ${FROM}ItemData.cpp $TO
$CP ${FROM}ItemData.h $TO
$CP ${FROM}MyString.cpp $TO
$CP ${FROM}MyString.h $TO
$CP ${FROM}PWCharPool.cpp $TO
$CP ${FROM}PWCharPool.h $TO
$CP ${FROM}Util.cpp $TO
$CP ${FROM}Util.h $TO
$CP ${FROM}sha1.cpp $TO
$CP ${FROM}sha1.h $TO

exit 0
