#!/bin/sh

gcc -m32 -fPIC -g -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda-5.5/include/ org/trifort/rootbeer/runtime/FixedMemory.c -o FixedMemory.o
gcc -m32 -shared -Wl,-soname,rootbeer -o rootbeer_x86.so.1 FixedMemory.o -lc

gcc -m32 -fPIC -g -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda-5.5/include/ org/trifort/rootbeer/runtime/CUDARuntime.c -o CUDARuntime.o
gcc -m32 -fPIC -g -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda-5.5/include/ org/trifort/rootbeer/runtime/CUDAContext.c -o CUDAContext.o
gcc -L/usr/lib32/nvidia-current/ -m32 -shared -Wl,-soname,rootbeer_cuda -o rootbeer_cuda_x86.so.1 CUDARuntime.o CUDAContext.o -lc -lcuda
