spot: spot::state Class Reference
spot::state Class Reference
Essential TGBA types
Abstract class for states.
#include <tgba/state.hh>
Public Member Functions
virtual int compare (const state *other) const =0
Compares two states (that come from the same automaton).
virtual size_t hash () const =0
Hash a state.
virtual state * clone () const =0
Duplicate a state.
virtual void destroy () const
Release a state.
Protected Member Functions
virtual ~state ()
Destructor.
Detailed Description
Abstract class for states.
Constructor & Destructor Documentation
virtual spot::state::~state () [inline, protected, virtual]
Destructor.
Deprecated:
Client code should now call s->destroy(); instead of delete s;.
Member Function Documentation
virtual state* spot::state::clone () const [pure virtual]
Duplicate a state.
Implemented in spot::state_evtgba_explicit, spot::state_kripke, spot::state_bdd, spot::state_set, spot::state_explicit, spot::state_product, and spot::state_union.
virtual int spot::state::compare (const state * other) const [pure virtual]
Compares two states (that come from the same automaton).
This method returns an integer less than, equal to, or greater than zero if this is found, respectively, to be less than, equal to, or greater than other according to some implicit total order.
This method should not be called to compare states from different automata.
See also:
spot::state_ptr_less_than
Implemented in spot::state_evtgba_explicit, spot::state_kripke, spot::state_bdd, spot::state_set, spot::state_explicit, spot::state_product, and spot::state_union.
Referenced by spot::state_ptr_equal::operator()(), and spot::state_ptr_less_than::operator()().
virtual void spot::state::destroy () const [inline, virtual]
Release a state.
Methods from the tgba or tgba_succ_iterator always return a new state that you should deallocate with this function. Before Spot 0.7, you had to "delete" your state directly. Starting with Spot 0.7, you update your code to this function instead (which simply calls "delete"). In a future version, some subclasses will redefine destroy() to allow better memory management (e.g. no memory allocation for explicit automata).
Reimplemented in spot::state_kripke, spot::state_explicit, and spot::state_product.
Referenced by spot::power_map::canonicalize(), spot::shared_state_deleter(), and spot::power_map::~power_map().
virtual size_t spot::state::hash () const [pure virtual]
Hash a state.
This method returns an integer that can be used as a hash value for this state.
Note that the hash value is guaranteed to be unique for all equal states (in compare()'s sense) for only has long has one of these states exists. So it's OK to use a spot::state as a key in a hash_map because the mere use of the state as a key in the hash will ensure the state continues to exist.
However if you create the state, get its hash key, delete the state, recreate the same state, and get its hash key, you may obtain two different hash keys if the same state were not already used elsewhere. In practice this weird situation can occur only when the state is BDD-encoded, because BDD numbers (used to build the hash value) can be reused for other formulas. That probably doesn't matter, since the hash value is meant to be used in a hash_map, but it had to be noted.
Implemented in spot::state_evtgba_explicit, spot::state_kripke, spot::state_bdd, spot::state_set, spot::state_explicit, spot::state_product, and spot::state_union.
Referenced by spot::state_ptr_hash::operator()().
The documentation for this class was generated from the following file:
tgba/state.hh
Please comment this page and report errors about it on the RefDocComments page.