spot: spot::acss_statistics Class Reference
spot::acss_statistics Class Reference
Emptiness-check statistics
Accepting Cycle Search Space statistics.
#include <tgbaalgos/emptiness_stats.hh>
Public Types
typedef unsigned(unsigned_statistics::* unsigned_fun)() const
typedef std::map< const char
*, unsigned_fun,
char_ptr_less_than > stats_map
Public Member Functions
acss_statistics ()
virtual ~acss_statistics ()
virtual unsigned acss_states () const =0
Number of states in the search space for the accepting cycle.
void inc_ars_prefix_states ()
unsigned ars_prefix_states () const
void inc_ars_cycle_states ()
unsigned ars_cycle_states () const
unsigned get (const char *str) const
Public Attributes
stats_map stats
Detailed Description
Accepting Cycle Search Space statistics.
Implementations of spot::emptiness_check_result may also implement this interface. Try to dynamic_cast the spot::emptiness_check_result pointer to know whether these statistics are available.
Member Typedef Documentation
typedef std::map<const char*, unsigned_fun, char_ptr_less_than> spot::unsigned_statistics::stats_map [inherited]
typedef unsigned(unsigned_statistics::* spot::unsigned_statistics::unsigned_fun)() const [inherited]
Constructor & Destructor Documentation
spot::acss_statistics::acss_statistics () [inline]
References acss_states(), and spot::unsigned_statistics::stats.
virtual spot::acss_statistics::~acss_statistics () [inline, virtual]
Member Function Documentation
virtual unsigned spot::acss_statistics::acss_states () const [pure virtual]
Number of states in the search space for the accepting cycle.
Implemented in spot::couvreur99_check_result.
Referenced by acss_statistics().
unsigned spot::ars_statistics::ars_cycle_states () const [inline, inherited]
References spot::ars_statistics::cycle_states_.
Referenced by spot::ars_statistics::ars_statistics().
unsigned spot::ars_statistics::ars_prefix_states () const [inline, inherited]
References spot::ars_statistics::prefix_states_.
Referenced by spot::ars_statistics::ars_statistics().
unsigned spot::unsigned_statistics::get (const char * str) const [inline, inherited]
References spot::unsigned_statistics::stats.
void spot::ars_statistics::inc_ars_cycle_states () [inline, inherited]
References spot::ars_statistics::cycle_states_.
void spot::ars_statistics::inc_ars_prefix_states () [inline, inherited]
References spot::ars_statistics::prefix_states_.
Member Data Documentation
stats_map spot::unsigned_statistics::stats [inherited]
Referenced by acss_statistics(), spot::ars_statistics::ars_statistics(), spot::ec_statistics::ec_statistics(), spot::unsigned_statistics::get(), and spot::unsigned_statistics_copy::seteq().
The documentation for this class was generated from the following file:
tgbaalgos/emptiness_stats.hh
Please comment this page and report errors about it on the RefDocComments page.