spot: spot::saba_state Class Reference
spot::saba_state Class Reference
Essential SABA types
Abstract class for saba states.
#include <saba/sabastate.hh>
Public Member Functions
virtual int compare (const saba_state *other) const =0
Compares two states (that come from the same automaton).
virtual size_t hash () const =0
Hash a state.
virtual saba_state * clone () const =0
Duplicate a state.
virtual bdd acceptance_conditions () const =0
Get the acceptance condition.
virtual ~saba_state ()
Detailed Description
Abstract class for saba states.
Constructor & Destructor Documentation
virtual spot::saba_state::~saba_state () [inline, virtual]
Member Function Documentation
virtual bdd spot::saba_state::acceptance_conditions () const [pure virtual]
Get the acceptance condition.
saba are state-labeled automata, then their acceptance conditions are labeled on states.
virtual saba_state* spot::saba_state::clone () const [pure virtual]
Duplicate a state.
virtual int spot::saba_state::compare (const saba_state * other) const [pure virtual]
Compares two states (that come from the same automaton).
This method returns an integer less than, equal to, or greater than zero if this is found, respectively, to be less than, equal to, or greater than other according to some implicit total order.
This method should not be called to compare states from different automata.
See also:
spot::saba_state_ptr_less_than
Referenced by spot::saba_state_ptr_equal::operator()(), and spot::saba_state_ptr_less_than::operator()().
virtual size_t spot::saba_state::hash () const [pure virtual]
Hash a state.
This method returns an integer that can be used as a hash value for this state.
Note that the hash value is guaranteed to be unique for all equal states (in compare()'s sense) for only has long has one of these states exists. So it's OK to use a spot::saba_state as a key in a hash_map because the mere use of the state as a key in the hash will ensure the state continues to exist.
However if you create the state, get its hash key, delete the state, recreate the same state, and get its hash key, you may obtain two different hash keys if the same state were not already used elsewhere. In practice this weird situation can occur only when the state is BDD-encoded, because BDD numbers (used to build the hash value) can be reused for other formulas. That probably doesn't matter, since the hash value is meant to be used in a hash_map, but it had to be noted.
Referenced by spot::saba_state_ptr_hash::operator()().
The documentation for this class was generated from the following file:
saba/sabastate.hh
Please comment this page and report errors about it on the RefDocComments page.