spot: eltlyy Namespace Reference
eltlyy Namespace Reference
Classes
class location
Abstract a location.
class position
Abstract a position.
class stack
class slice
Present a slice of the top of a stack.
Functions
const location operator+ (const location &begin, const location &end)
Join two location objects to create a location.
const location operator+ (const location &begin, unsigned int width)
Add two location objects.
location & operator+= (location &res, unsigned int width)
Add and assign a location.
bool operator== (const location &loc1, const location &loc2)
Compare two location objects.
bool operator!= (const location &loc1, const location &loc2)
Compare two location objects.
std::ostream & operator<< (std::ostream &ostr, const location &loc)
Intercept output stream redirection.
const position & operator+= (position &res, const int width)
Add and assign a position.
const position operator+ (const position &begin, const int width)
Add two position objects.
const position & operator-= (position &res, const int width)
Add and assign a position.
const position operator- (const position &begin, const int width)
Add two position objects.
bool operator== (const position &pos1, const position &pos2)
Compare two position objects.
bool operator!= (const position &pos1, const position &pos2)
Compare two position objects.
std::ostream & operator<< (std::ostream &ostr, const position &pos)
Intercept output stream redirection.
Function Documentation
bool eltlyy::operator!= (const location & loc1, const location & loc2) [inline]
Compare two location objects.
bool eltlyy::operator!= (const position & pos1, const position & pos2) [inline]
Compare two position objects.
const location eltlyy::operator+ (const location & begin, const location & end) [inline]
Join two location objects to create a location.
References eltlyy::location::end.
const position eltlyy::operator+ (const position & begin, const int width) [inline]
Add two position objects.
const location eltlyy::operator+ (const location & begin, unsigned int width) [inline]
Add two location objects.
References eltlyy::location::columns().
location& eltlyy::operator+= (location & res, unsigned int width) [inline]
Add and assign a location.
References eltlyy::location::columns().
const position& eltlyy::operator+= (position & res, const int width) [inline]
Add and assign a position.
References eltlyy::position::columns().
const position eltlyy::operator- (const position & begin, const int width) [inline]
Add two position objects.
const position& eltlyy::operator-= (position & res, const int width) [inline]
Add and assign a position.
std::ostream& eltlyy::operator<< (std::ostream & ostr, const location & loc) [inline]
Intercept output stream redirection.
Parameters:
ostr the destination output stream
loc a reference to the location to redirect
Avoid duplicate information.
References eltlyy::location::begin, eltlyy::position::column, eltlyy::location::end, eltlyy::position::filename, and eltlyy::position::line.
std::ostream& eltlyy::operator<< (std::ostream & ostr, const position & pos) [inline]
Intercept output stream redirection.
Parameters:
ostr the destination output stream
pos a reference to the position to redirect
References eltlyy::position::column, eltlyy::position::filename, and eltlyy::position::line.
bool eltlyy::operator== (const location & loc1, const location & loc2) [inline]
Compare two location objects.
References eltlyy::location::begin, and eltlyy::location::end.
bool eltlyy::operator== (const position & pos1, const position & pos2) [inline]
Compare two position objects.
References eltlyy::position::column, eltlyy::position::filename, and eltlyy::position::line.
Please comment this page and report errors about it on the RefDocComments page.