spot: ltlyy Namespace Reference
ltlyy Namespace Reference
Classes
class location
Abstract a location.
class position
Abstract a position.
class stack
class slice
Present a slice of the top of a stack.
Functions
const location operator+ (const location &begin, const location &end)
Join two location objects to create a location.
const location operator+ (const location &begin, unsigned int width)
Add two location objects.
location & operator+= (location &res, unsigned int width)
Add and assign a location.
bool operator== (const location &loc1, const location &loc2)
Compare two location objects.
bool operator!= (const location &loc1, const location &loc2)
Compare two location objects.
std::ostream & operator<< (std::ostream &ostr, const location &loc)
Intercept output stream redirection.
const position & operator+= (position &res, const int width)
Add and assign a position.
const position operator+ (const position &begin, const int width)
Add two position objects.
const position & operator-= (position &res, const int width)
Add and assign a position.
const position operator- (const position &begin, const int width)
Add two position objects.
bool operator== (const position &pos1, const position &pos2)
Compare two position objects.
bool operator!= (const position &pos1, const position &pos2)
Compare two position objects.
std::ostream & operator<< (std::ostream &ostr, const position &pos)
Intercept output stream redirection.
Function Documentation
bool ltlyy::operator!= (const location & loc1, const location & loc2) [inline]
Compare two location objects.
bool ltlyy::operator!= (const position & pos1, const position & pos2) [inline]
Compare two position objects.
const location ltlyy::operator+ (const location & begin, const location & end) [inline]
Join two location objects to create a location.
References ltlyy::location::end.
const position ltlyy::operator+ (const position & begin, const int width) [inline]
Add two position objects.
const location ltlyy::operator+ (const location & begin, unsigned int width) [inline]
Add two location objects.
References ltlyy::location::columns().
location& ltlyy::operator+= (location & res, unsigned int width) [inline]
Add and assign a location.
References ltlyy::location::columns().
const position& ltlyy::operator+= (position & res, const int width) [inline]
Add and assign a position.
References ltlyy::position::columns().
const position ltlyy::operator- (const position & begin, const int width) [inline]
Add two position objects.
const position& ltlyy::operator-= (position & res, const int width) [inline]
Add and assign a position.
std::ostream& ltlyy::operator<< (std::ostream & ostr, const location & loc) [inline]
Intercept output stream redirection.
Parameters:
ostr the destination output stream
loc a reference to the location to redirect
Avoid duplicate information.
References ltlyy::location::begin, ltlyy::position::column, ltlyy::location::end, ltlyy::position::filename, and ltlyy::position::line.
std::ostream& ltlyy::operator<< (std::ostream & ostr, const position & pos) [inline]
Intercept output stream redirection.
Parameters:
ostr the destination output stream
pos a reference to the position to redirect
References ltlyy::position::column, ltlyy::position::filename, and ltlyy::position::line.
bool ltlyy::operator== (const location & loc1, const location & loc2) [inline]
Compare two location objects.
References ltlyy::location::begin, and ltlyy::location::end.
bool ltlyy::operator== (const position & pos1, const position & pos2) [inline]
Compare two position objects.
References ltlyy::position::column, ltlyy::position::filename, and ltlyy::position::line.
Please comment this page and report errors about it on the RefDocComments page.