#!/bin/sh

CFLAGS="-fno-common -Os -arch i386 -arch x86_64"
LDFLAGS="-arch i386 -arch x86_64 -dynamiclib"

rm -f *.o
llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ CudaRuntime2.c -o CudaRuntime2.o
llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ FastMemory.c -o FastMemory.o
llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ Handles.c -o Handles.o
llvm-gcc $CFLAGS -g -c -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I/usr/local/cuda/include/ Cuda2DeviceMemory.c -o Cuda2DeviceMemory.o
llvm-gcc $LDFLAGS -o cudaruntime.dylib -dylib CudaRuntime2.o FastMemory.o Handles.o Cuda2DeviceMemory.o -lc -lcuda -L/usr/local/cuda/lib

cp cudaruntime.dylib ../src/edu/syr/pcpratts/rootbeer/runtime2/native/
cp cudaruntime.dylib ..
