spot: spot::ta_check Class Reference
spot::ta_check Class Reference
Emptiness-checks
An implementation of the emptiness-check algorithm for a product between a TA and a Kripke structure.
#include <taalgos/emptinessta.hh>
Public Types
typedef unsigned(unsigned_statistics::* unsigned_fun)() const
typedef std::map< const char
*, unsigned_fun,
char_ptr_less_than > stats_map
Public Member Functions
virtual ~ta_check ()
virtual bool check (bool disable_second_pass=false, bool disable_heuristic_for_livelock_detection=false)
Check whether the TA product automaton contains an accepting run: it detects the two kinds of accepting runs: Buchi-accepting runs and livelock-accepting runs. This emptiness check algorithm can also check a product using the generalized form of TA.
virtual bool livelock_detection (const ta_product *t)
Check whether the product automaton contains a livelock-accepting run Return false if the product automaton accepts no livelock-accepting run, otherwise true.
virtual std::ostream & print_stats (std::ostream &os) const
Print statistics, if any.
void set_states (unsigned n)
void inc_states ()
void inc_transitions ()
void inc_depth (unsigned n=1)
void dec_depth (unsigned n=1)
unsigned states () const
unsigned transitions () const
unsigned max_depth () const
unsigned depth () const
unsigned get (const char *str) const
Static Public Member Functions
ta_check (const ta_product *a, option_map o=option_map())
Public Attributes
stats_map stats
Protected Member Functions
void clear (numbered_state_heap *h, std::stack< pair_state_iter > todo, std::queue< spot::state * > init_set)
void clear (numbered_state_heap *h, std::stack< pair_state_iter > todo, spot::ta_succ_iterator *init_states_it)
bool heuristic_livelock_detection (const state *stuttering_succ, numbered_state_heap *h, int h_livelock_root, std::set< const state *, state_ptr_less_than > liveset_curr)
Protected Attributes
const ta_product * a_
The automaton.
option_map o_
The options.
bool is_full_2_pass_
scc_stack_ta scc
scc_stack_ta sscc
Detailed Description
An implementation of the emptiness-check algorithm for a product between a TA and a Kripke structure.
See the paper cited above.
Member Typedef Documentation
typedef std::map<const char*, unsigned_fun, char_ptr_less_than> spot::unsigned_statistics::stats_map inherited
typedef unsigned(unsigned_statistics::* spot::unsigned_statistics::unsigned_fun)() const inherited
Constructor & Destructor Documentation
spot::ta_check::ta_check (const ta_product * a, option_map o = option_map()) static
virtual spot::ta_check::~ta_check () virtual
Member Function Documentation
virtual bool spot::ta_check::check (bool disable_second_pass = false, bool disable_heuristic_for_livelock_detection = false) virtual
Check whether the TA product automaton contains an accepting run: it detects the two kinds of accepting runs: Buchi-accepting runs and livelock-accepting runs. This emptiness check algorithm can also check a product using the generalized form of TA.
Return false if the product automaton accepts no run, otherwise true
Parameters
disable_second_pass,: is used to disable the second pass when when it is not necessary, for example when all the livelock-accepting states of the TA automaton have no successors, we call this kind of TA as STA (Single-pass Testing Automata) (see spot::tgba2ta::add_artificial_livelock_accepting_state() for an automatic transformation of any TA automaton into STA automaton
disable_heuristic_for_livelock_detection,: disable the heuristic used in the first pass to detect livelock-accepting runs, this heuristic is described in the paper cited above
void spot::ta_check::clear (numbered_state_heap * h, std::stack< pair_state_iter > todo, std::queue< spot::state * > init_set) protected
void spot::ta_check::clear (numbered_state_heap * h, std::stack< pair_state_iter > todo, spot::ta_succ_iterator * init_states_it) protected
void spot::ec_statistics::dec_depth (unsigned n = 1) inline inherited
References spot::ec_statistics::depth_.
unsigned spot::ec_statistics::depth () const inline inherited
References spot::ec_statistics::depth_.
unsigned spot::unsigned_statistics::get (const char * str) const inline inherited
References spot::unsigned_statistics::stats.
bool spot::ta_check::heuristic_livelock_detection (const state * stuttering_succ, numbered_state_heap * h, int h_livelock_root, std::set< const state *, state_ptr_less_than > liveset_curr) protected
the heuristic for livelock-accepting runs detection, it's described in the paper cited above
void spot::ec_statistics::inc_depth (unsigned n = 1) inline inherited
References spot::ec_statistics::depth_, and spot::ec_statistics::max_depth_.
void spot::ec_statistics::inc_states () inline inherited
References spot::ec_statistics::states_.
void spot::ec_statistics::inc_transitions () inline inherited
References spot::ec_statistics::transitions_.
virtual bool spot::ta_check::livelock_detection (const ta_product * t) virtual
Check whether the product automaton contains a livelock-accepting run Return false if the product automaton accepts no livelock-accepting run, otherwise true.
unsigned spot::ec_statistics::max_depth () const inline inherited
References spot::ec_statistics::max_depth_.
Referenced by spot::ec_statistics::ec_statistics().
virtual std::ostream& spot::ta_check::print_stats (std::ostream & os) const virtual
Print statistics, if any.
void spot::ec_statistics::set_states (unsigned n) inline inherited
References spot::ec_statistics::states_.
unsigned spot::ec_statistics::states () const inline inherited
References spot::ec_statistics::states_.
Referenced by spot::ec_statistics::ec_statistics().
unsigned spot::ec_statistics::transitions () const inline inherited
References spot::ec_statistics::transitions_.
Referenced by spot::ec_statistics::ec_statistics().
Member Data Documentation
const ta_product* spot::ta_check::a_ protected
The automaton.
bool spot::ta_check::is_full_2_pass_ protected
option_map spot::ta_check::o_ protected
The options.
scc_stack_ta spot::ta_check::scc protected
scc_stack_ta spot::ta_check::sscc protected
stats_map spot::unsigned_statistics::stats inherited
Referenced by spot::acss_statistics::acss_statistics(), spot::ars_statistics::ars_statistics(), spot::ec_statistics::ec_statistics(), spot::unsigned_statistics::get(), and spot::unsigned_statistics_copy::seteq().
The documentation for this class was generated from the following file:
taalgos/emptinessta.hh
Please comment this page and report errors about it on the RefDocComments page.