spot: spot::barand< gen > Class Template Reference
spot::barand< gen > Class Template Reference
Random functions
Compute pseudo-random integer value between 0 and n included, following a binomial distribution for probability p.
#include <misc/random.hh>
Public Member Functions
barand (int n, double p)
int rand () const
Protected Attributes
const int n_
const double m_
const double s_
Detailed Description
template<double(*)() gen>
class spot::barand< gen >
Compute pseudo-random integer value between 0 and n included, following a binomial distribution for probability p.
gen must be a random function computing a pseudo-random double value following a standard normal distribution. Use nrand() or bmrand().
Usually approximating a binomial distribution using a normal distribution and is accurate only if n*p and n*(1-p) are greater than 5.
Constructor & Destructor Documentation
template<double(*)() gen> spot::barand< gen >::barand (int n, double p) inline
Member Function Documentation
template<double(*)() gen> int spot::barand< gen >::rand () const inline
References spot::barand< gen >::m_, spot::barand< gen >::n_, and spot::barand< gen >::s_.
Member Data Documentation
template<double(*)() gen> const double spot::barand< gen >::m_ protected
Referenced by spot::barand< gen >::rand().
template<double(*)() gen> const int spot::barand< gen >::n_ protected
Referenced by spot::barand< gen >::rand().
template<double(*)() gen> const double spot::barand< gen >::s_ protected
Referenced by spot::barand< gen >::rand().
The documentation for this class was generated from the following file:
misc/random.hh
Please comment this page and report errors about it on the RefDocComments page.