spot: spot::tgba_explicit_succ_iterator< State > Class Template Reference
spot::tgba_explicit_succ_iterator< State > Class Template Reference
TGBA representations
#include <tgba/tgbaexplicit.hh>
Public Member Functions
tgba_explicit_succ_iterator (const State *start, bdd all_acc)
virtual void first ()
Position the iterator on the first successor (if any).
virtual void next ()
Jump to the next successor (if any).
virtual bool done () const
Check whether the iteration is finished.
virtual State * current_state () const
Get the state of the current successor.
virtual bdd current_condition () const
Get the condition on the transition leading to this successor.
virtual bdd current_acceptance_conditions () const
Get the acceptance conditions on the transition leading to this successor.
State::transitions_t::const_iterator get_iterator () const
Private Attributes
const State * start_
State::transitions_t::const_iterator it_
bdd all_acceptance_conditions_
Detailed Description
template<typename State>
class spot::tgba_explicit_succ_iterator< State >
Successor iterators used by spot::tgba_explicit.
Constructor & Destructor Documentation
template<typename State> spot::tgba_explicit_succ_iterator< State >::tgba_explicit_succ_iterator (const State * start, bdd all_acc) inline
Member Function Documentation
template<typename State> virtual bdd spot::tgba_explicit_succ_iterator< State >::current_acceptance_conditions () const inline virtual
Get the acceptance conditions on the transition leading to this successor.
Implements spot::tgba_succ_iterator.
References spot::tgba_explicit_succ_iterator< State >::done(), and spot::tgba_explicit_succ_iterator< State >::it_.
template<typename State> virtual bdd spot::tgba_explicit_succ_iterator< State >::current_condition () const inline virtual
Get the condition on the transition leading to this successor.
This is a boolean function of atomic propositions.
Implements spot::tgba_succ_iterator.
References spot::tgba_explicit_succ_iterator< State >::done(), and spot::tgba_explicit_succ_iterator< State >::it_.
template<typename State> virtual State* spot::tgba_explicit_succ_iterator< State >::current_state () const inline virtual
Get the state of the current successor.
Note that the same state may occur at different points in the iteration. These actually correspond to the same destination. It just means there were several transitions, with different conditions, leading to the same state.
The returned state should be destroyed (see state::destroy) by the caller after it is no longer used.
Implements spot::tgba_succ_iterator.
References spot::tgba_explicit_succ_iterator< State >::done(), down_cast, and spot::tgba_explicit_succ_iterator< State >::it_.
template<typename State> virtual bool spot::tgba_explicit_succ_iterator< State >::done () const inline virtual
Check whether the iteration is finished.
   This function should be called after any call to \c first()
   or \c next() and before any enquiry about the current state.
   The usual way to do this is with a \c for loop.
   @code
for (s->first(); !s->done(); s->next()) ...
Implements spot::tgba_succ_iterator.
References spot::tgba_explicit_succ_iterator< State >::it_, and spot::tgba_explicit_succ_iterator< State >::start_.
Referenced by spot::tgba_explicit_succ_iterator< State >::current_acceptance_conditions(), spot::tgba_explicit_succ_iterator< State >::current_condition(), and spot::tgba_explicit_succ_iterator< State >::current_state().
template<typename State> virtual void spot::tgba_explicit_succ_iterator< State >::first () inline virtual
Position the iterator on the first successor (if any).
This method can be called several times to make multiple passes over successors.
Warning
One should always call done() to ensure there is a successor, even after first(). A common trap is to assume that there is at least one successor: this is wrong.
Implements spot::tgba_succ_iterator.
References spot::tgba_explicit_succ_iterator< State >::it_, and spot::tgba_explicit_succ_iterator< State >::start_.
template<typename State> State::transitions_t::const_iterator spot::tgba_explicit_succ_iterator< State >::get_iterator () const inline
References spot::tgba_explicit_succ_iterator< State >::it_.
Referenced by spot::explicit_graph< State, tgba >::get_transition().
template<typename State> virtual void spot::tgba_explicit_succ_iterator< State >::next () inline virtual
Jump to the next successor (if any).
Warning
Again, one should always call done() to ensure there is a successor.
Implements spot::tgba_succ_iterator.
References spot::tgba_explicit_succ_iterator< State >::it_.
Member Data Documentation
template<typename State> bdd spot::tgba_explicit_succ_iterator< State >::all_acceptance_conditions_ private
template<typename State> State::transitions_t::const_iterator spot::tgba_explicit_succ_iterator< State >::it_ private
Referenced by spot::tgba_explicit_succ_iterator< State >::current_acceptance_conditions(), spot::tgba_explicit_succ_iterator< State >::current_condition(), spot::tgba_explicit_succ_iterator< State >::current_state(), spot::tgba_explicit_succ_iterator< State >::done(), spot::tgba_explicit_succ_iterator< State >::first(), spot::tgba_explicit_succ_iterator< State >::get_iterator(), and spot::tgba_explicit_succ_iterator< State >::next().
template<typename State> const State* spot::tgba_explicit_succ_iterator< State >::start_ private
Referenced by spot::tgba_explicit_succ_iterator< State >::done(), and spot::tgba_explicit_succ_iterator< State >::first().
The documentation for this class was generated from the following file:
tgba/tgbaexplicit.hh
Please comment this page and report errors about it on the RefDocComments page.