spot: spot::state_ta_product Class Reference
spot::state_ta_product Class Reference
Emptiness-checks
A state for spot::ta_product.This state is in fact a pair of state: the state from the TA automaton and that of Kripke structure.
#include <ta/taproduct.hh>
Public Member Functions
state_ta_product (state *ta_state, state *kripke_state)
Constructor.
state_ta_product (const state_ta_product &o)
Copy constructor.
virtual ~state_ta_product ()
state * get_ta_state () const
state * get_kripke_state () const
virtual int compare (const state *other) const
Compares two states (that come from the same automaton).
virtual size_t hash () const
Hash a state.
virtual state_ta_product * clone () const
Duplicate a state.
virtual void destroy () const
Release a state.
Private Attributes
state * ta_state_
State from the ta automaton.
state * kripke_state_
State from the kripke structure.
Detailed Description
A state for spot::ta_product.
This state is in fact a pair of state: the state from the TA automaton and that of Kripke structure.
Constructor & Destructor Documentation
spot::state_ta_product::state_ta_product (state * ta_state, state * kripke_state) inline
Constructor.
Parameters
ta_state The state from the ta automaton.
kripke_state_ The state from Kripke structure.
spot::state_ta_product::state_ta_product (const state_ta_product & o)
Copy constructor.
virtual spot::state_ta_product::~state_ta_product () virtual
Member Function Documentation
virtual state_ta_product* spot::state_ta_product::clone () const virtual
Duplicate a state.
Implements spot::state.
virtual int spot::state_ta_product::compare (const state * other) const virtual
Compares two states (that come from the same automaton).
This method returns an integer less than, equal to, or greater than zero if this is found, respectively, to be less than, equal to, or greater than other according to some implicit total order.
This method should not be called to compare states from different automata.
See Also
spot::state_ptr_less_than
Implements spot::state.
virtual void spot::state::destroy () const inline virtual inherited
Release a state.
Methods from the tgba or tgba_succ_iterator always return a new state that you should deallocate with this function. Before Spot 0.7, you had to "delete" your state directly. Starting with Spot 0.7, you update your code to this function instead (which simply calls "delete"). In a future version, some subclasses will redefine destroy() to allow better memory management (e.g. no memory allocation for explicit automata).
Reimplemented in spot::state_ta_explicit, spot::state_explicit< Label, label_hash >, spot::state_explicit< const ltl::formula *, ltl::formula_ptr_hash >, spot::state_explicit< int, identity_hash< int > >, spot::state_explicit< std::string, string_hash >, and spot::state_product.
Referenced by spot::power_map::canonicalize(), spot::shared_state_deleter(), and spot::power_map::~power_map().
state* spot::state_ta_product::get_kripke_state () const inline
References kripke_state_.
state* spot::state_ta_product::get_ta_state () const inline
References ta_state_.
virtual size_t spot::state_ta_product::hash () const virtual
Hash a state.
This method returns an integer that can be used as a hash value for this state.
Note that the hash value is guaranteed to be unique for all equal states (in compare()'s sense) for only has long has one of these states exists. So it's OK to use a spot::state as a key in a hash_map because the mere use of the state as a key in the hash will ensure the state continues to exist.
However if you create the state, get its hash key, delete the state, recreate the same state, and get its hash key, you may obtain two different hash keys if the same state were not already used elsewhere. In practice this weird situation can occur only when the state is BDD-encoded, because BDD numbers (used to build the hash value) can be reused for other formulas. That probably doesn't matter, since the hash value is meant to be used in a hash_map, but it had to be noted.
Implements spot::state.
Member Data Documentation
state* spot::state_ta_product::kripke_state_ private
State from the kripke structure.
Referenced by get_kripke_state().
state* spot::state_ta_product::ta_state_ private
State from the ta automaton.
Referenced by get_ta_state().
The documentation for this class was generated from the following file:
ta/taproduct.hh
Please comment this page and report errors about it on the RefDocComments page.