spot: spot::stat_printer Class Reference
spot::stat_printer Class Reference
Miscellaneous algorithms on TGBA
prints various statistics about a TGBA
#include <tgbaalgos/stats.hh>
Public Member Functions
stat_printer (std::ostream &os, const char *format)
std::ostream & print (const tgba *aut, const ltl::formula *f=0)
print the configured statistics.
Protected Member Functions
void prime (const char *fmt)
Collect the %-sequences occurring in fmt.
void prime (const std::string &fmt)
Collect the %-sequences occurring in fmt.
bool has (char c) const
Whether c occurred in the primed formats.
void declare (char c, const printable *f)
Declare a callback function for c.
void set_output (std::ostream &output)
Remember where to output any string.
std::ostream & format (const char *fmt)
Expand the %-sequences in fmt, write the result on output_.
std::ostream & format (std::ostream &output, const char *fmt)
Expand the %-sequences in fmt, write the result on output.
std::ostream & format (const std::string &fmt)
Expand the %-sequences in fmt, write the result on output_.
std::ostream & format (std::ostream &output, const std::string &fmt)
Expand the %-sequences in fmt, write the result on output.
Protected Attributes
std::ostream * output_
const char * pos_
Private Attributes
const char * format_
printable_formula form_
printable_value< unsigned > states_
printable_value< unsigned > edges_
printable_value< unsigned > trans_
printable_value< unsigned > acc_
printable_value< unsigned > scc_
printable_value< unsigned > nondetstates_
printable_value< unsigned > deterministic_
Detailed Description
prints various statistics about a TGBA
This object can be configured to display various statistics about a TGBA. Some %-sequence of characters are interpreted in the format string, and replaced by the corresponding statistics.
Constructor & Destructor Documentation
spot::stat_printer::stat_printer (std::ostream & os, const char * format)
Member Function Documentation
void spot::formater::declare (char c, const printable * f) inline inherited
Declare a callback function for c.
References spot::formater::call_.
std::ostream& spot::formater::format (const char * fmt) inherited
Expand the %-sequences in fmt, write the result on output_.
Referenced by spot::formater::format().
std::ostream& spot::formater::format (std::ostream & output, const char * fmt) inline inherited
Expand the %-sequences in fmt, write the result on output.
References spot::formater::format(), and spot::formater::set_output().
std::ostream& spot::formater::format (const std::string & fmt) inline inherited
Expand the %-sequences in fmt, write the result on output_.
References spot::formater::format().
std::ostream& spot::formater::format (std::ostream & output, const std::string & fmt) inline inherited
Expand the %-sequences in fmt, write the result on output.
References spot::formater::format().
bool spot::formater::has (char c) const inline inherited
Whether c occurred in the primed formats.
References spot::formater::has_.
void spot::formater::prime (const char * fmt) inherited
Collect the %-sequences occurring in fmt.
Referenced by spot::formater::prime().
void spot::formater::prime (const std::string & fmt) inline inherited
Collect the %-sequences occurring in fmt.
References spot::formater::prime().
std::ostream& spot::stat_printer::print (const tgba * aut, const ltl::formula * f = 0)
print the configured statistics.
The f argument is not needed if the Formula does not need to be output.
void spot::formater::set_output (std::ostream & output) inline inherited
Remember where to output any string.
References spot::formater::output_.
Referenced by spot::formater::format().
Member Data Documentation
printable_value<unsigned> spot::stat_printer::acc_ private
printable_value<unsigned> spot::stat_printer::deterministic_ private
printable_value<unsigned> spot::stat_printer::edges_ private
printable_formula spot::stat_printer::form_ private
const char* spot::stat_printer::format_ private
printable_value<unsigned> spot::stat_printer::nondetstates_ private
std::ostream* spot::formater::output_ protected inherited
Referenced by spot::formater::set_output().
const char* spot::formater::pos_ protected inherited
printable_value<unsigned> spot::stat_printer::scc_ private
printable_value<unsigned> spot::stat_printer::states_ private
printable_value<unsigned> spot::stat_printer::trans_ private
The documentation for this class was generated from the following file:
tgbaalgos/stats.hh
Please comment this page and report errors about it on the RefDocComments page.