spot: spot::rsymbol Class Reference
spot::rsymbol Class Reference
#include <evtgba/symbol.hh>
Public Member Functions
rsymbol (const symbol *s)
rsymbol (const std::string &s)
rsymbol (const char *s)
rsymbol (const rsymbol &rs)
~rsymbol ()
operator const symbol * () const
const rsymbol & operator= (const rsymbol &rs)
bool operator== (const rsymbol &rs) const
bool operator!= (const rsymbol &rs) const
bool operator< (const rsymbol &rs) const
Private Attributes
const symbol * s_
Constructor & Destructor Documentation
spot::rsymbol::rsymbol (const symbol * s) inline
Referenced by operator=().
spot::rsymbol::rsymbol (const std::string & s) inline
spot::rsymbol::rsymbol (const char * s) inline
spot::rsymbol::rsymbol (const rsymbol & rs) inline
References spot::symbol::ref(), and s_.
spot::rsymbol::~rsymbol () inline
References s_, and spot::symbol::unref().
Referenced by operator=().
Member Function Documentation
spot::rsymbol::operator const symbol * () const inline
References s_.
bool spot::rsymbol::operator!= (const rsymbol & rs) const inline
References s_.
bool spot::rsymbol::operator< (const rsymbol & rs) const inline
References s_.
const rsymbol& spot::rsymbol::operator= (const rsymbol & rs) inline
References rsymbol(), and ~rsymbol().
bool spot::rsymbol::operator== (const rsymbol & rs) const inline
References s_.
Member Data Documentation
const symbol* spot::rsymbol::s_ private
Referenced by operator const symbol *(), operator!=(), operator<(), operator==(), rsymbol(), and ~rsymbol().
The documentation for this class was generated from the following file:
evtgba/symbol.hh
Please comment this page and report errors about it on the RefDocComments page.