/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trifort_rootbeer_runtime_CUDARuntime */

#ifndef _Included_org_trifort_rootbeer_runtime_CUDARuntime
#define _Included_org_trifort_rootbeer_runtime_CUDARuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trifort_rootbeer_runtime_CUDARuntime
 * Method:    loadGpuDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_trifort_rootbeer_runtime_CUDARuntime_loadGpuDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
