#!/bin/sh
for i in 3 4 5 6 8 ; do
  sfx=$i
  . templates/common
  PRS=`seq 1 $i | sed 's/^/pr/;s/$/,/' | tr -d '\n' | sed 's/,$//'`
  echo "	sed 's/@PR@/$PRS/' '\$(srcdir)/$name/$bname.def' > '$dst/$bname$sfx.def'" >>tmp$$
  echo "	sed 's/:.*//' '\$(srcdir)/$name/$bname.prop' | tr '\n' ' ' > '$dst/$bname$sfx.ap'" >>tmp$$
  FILES="$FILES $name/$bname.def $name/$bname.prop"
  finish
done
