/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trifort_rootbeer_runtime_FixedMemory */

#ifndef _Included_org_trifort_rootbeer_runtime_FixedMemory
#define _Included_org_trifort_rootbeer_runtime_FixedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadByteArray
 * Signature: ([BJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadByteArray
  (JNIEnv *, jobject, jbyteArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadBooleanArray
 * Signature: ([ZJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadBooleanArray
  (JNIEnv *, jobject, jbooleanArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadShortArray
 * Signature: ([SJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadShortArray
  (JNIEnv *, jobject, jshortArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadIntArray
 * Signature: ([IJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadIntArray
  (JNIEnv *, jobject, jintArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadFloatArray
 * Signature: ([FJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadFloatArray
  (JNIEnv *, jobject, jfloatArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadDoubleArray
 * Signature: ([DJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadDoubleArray
  (JNIEnv *, jobject, jdoubleArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadLongArray
 * Signature: ([JJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadLongArray
  (JNIEnv *, jobject, jlongArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteByteArray
 * Signature: ([BJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteByteArray
  (JNIEnv *, jobject, jbyteArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteBooleanArray
 * Signature: ([ZJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteBooleanArray
  (JNIEnv *, jobject, jbooleanArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteShortArray
 * Signature: ([SJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteShortArray
  (JNIEnv *, jobject, jshortArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteIntArray
 * Signature: ([IJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteIntArray
  (JNIEnv *, jobject, jintArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteFloatArray
 * Signature: ([FJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteFloatArray
  (JNIEnv *, jobject, jfloatArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteDoubleArray
 * Signature: ([DJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteDoubleArray
  (JNIEnv *, jobject, jdoubleArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteLongArray
 * Signature: ([JJII)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteLongArray
  (JNIEnv *, jobject, jlongArray, jlong, jint, jint);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadByte
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadByte
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadBoolean
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadBoolean
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadShort
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadShort
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadInt
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doReadLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doReadLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteByte
 * Signature: (JBJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteByte
  (JNIEnv *, jobject, jlong, jbyte, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteBoolean
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteBoolean
  (JNIEnv *, jobject, jlong, jboolean, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteShort
 * Signature: (JSJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteShort
  (JNIEnv *, jobject, jlong, jshort, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteInt
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteInt
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteFloat
 * Signature: (JFJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteFloat
  (JNIEnv *, jobject, jlong, jfloat, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteDouble
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteDouble
  (JNIEnv *, jobject, jlong, jdouble, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    doWriteLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_doWriteLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_malloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_trifort_rootbeer_runtime_FixedMemory
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_trifort_rootbeer_runtime_FixedMemory_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
