/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles */

#ifndef _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
#define _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
 * Method:    setup
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles_setup
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
 * Method:    resetPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles_resetPointer
  (JNIEnv *, jobject);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
 * Method:    writeLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles_writeLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
 * Method:    readLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles_readLong
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
