/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_rootbeer_runtime_memory_BatchIntReader */

#ifndef _Included_edu_syr_pcpratts_rootbeer_runtime_memory_BatchIntReader
#define _Included_edu_syr_pcpratts_rootbeer_runtime_memory_BatchIntReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime_memory_BatchIntReader
 * Method:    read
 * Signature: ([BI[I)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime_memory_BatchIntReader_read
  (JNIEnv *, jobject, jbyteArray, jint, jintArray);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime_memory_BatchIntReader
 * Method:    malloc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime_memory_BatchIntReader_malloc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
