/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_rootbeer_runtime_nativecpu_NativeCpuDevice */

#ifndef _Included_edu_syr_pcpratts_rootbeer_runtime_nativecpu_NativeCpuDevice
#define _Included_edu_syr_pcpratts_rootbeer_runtime_nativecpu_NativeCpuDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime_nativecpu_NativeCpuDevice
 * Method:    runOnCpu
 * Signature: (Ljava/util/List;I[B[B[B[BILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime_nativecpu_NativeCpuDevice_runOnCpu
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
