#line 2 "ltlscan.cc"

#line 4 "ltlscan.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ltlyy_create_buffer
#define yy_delete_buffer ltlyy_delete_buffer
#define yy_flex_debug ltlyy_flex_debug
#define yy_init_buffer ltlyy_init_buffer
#define yy_flush_buffer ltlyy_flush_buffer
#define yy_load_buffer_state ltlyy_load_buffer_state
#define yy_switch_to_buffer ltlyy_switch_to_buffer
#define yyin ltlyyin
#define yyleng ltlyyleng
#define yylex ltlyylex
#define yylineno ltlyylineno
#define yyout ltlyyout
#define yyrestart ltlyyrestart
#define yytext ltlyytext
#define yywrap ltlyywrap
#define yyalloc ltlyyalloc
#define yyrealloc ltlyyrealloc
#define yyfree ltlyyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ltlyyrestart(ltlyyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t ltlyyleng;

extern FILE *ltlyyin, *ltlyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ltlyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ltlyytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ltlyyrestart()), so that the user can continue scanning by
	 * just pointing ltlyyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ltlyytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t ltlyyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ltlyywrap()'s to do buffer switches
 * instead of setting up a fresh ltlyyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ltlyyrestart (FILE *input_file  );
void ltlyy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ltlyy_create_buffer (FILE *file,int size  );
void ltlyy_delete_buffer (YY_BUFFER_STATE b  );
void ltlyy_flush_buffer (YY_BUFFER_STATE b  );
void ltlyypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void ltlyypop_buffer_state (void );

static void ltlyyensure_buffer_stack (void );
static void ltlyy_load_buffer_state (void );
static void ltlyy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ltlyy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ltlyy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ltlyy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ltlyy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *ltlyyalloc (yy_size_t  );
void *ltlyyrealloc (void *,yy_size_t  );
void ltlyyfree (void *  );

#define yy_new_buffer ltlyy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ltlyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ltlyy_create_buffer(ltlyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ltlyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ltlyy_create_buffer(ltlyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define ltlyywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *ltlyyin = (FILE *) 0, *ltlyyout = (FILE *) 0;

typedef int yy_state_type;

extern int ltlyylineno;

int ltlyylineno = 1;

extern char *ltlyytext;
#define yytext_ptr ltlyytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ltlyytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ltlyyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[196] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   58,   56,   47,   47,   15,   56,   34,    1,
       10,   22,   32,   56,   48,   56,   14,   13,   21,   20,
       56,   56,   38,   39,   44,   41,   48,   40,   43,   42,
       56,   56,   35,   48,   48,    5,   32,   12,   56,   56,
       56,   50,   38,   39,   44,   41,   50,   40,   43,   42,
       50,   50,    4,    4,    4,    2,    3,    9,    9,    9,
        6,    8,   31,   30,   56,   29,   28,   56,   56,   56,
       54,   53,   47,    0,   52,   33,   42,    0,   36,   48,
        0,    0,   38,   45,   46,   36,   49,    0,   48,   25,

        0,    0,   26,   39,    0,   32,   48,   48,    0,    0,
        0,    0,   11,   15,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   50,   50,   50,   50,    4,
        4,    9,    9,    0,    7,   30,   29,    0,    0,   55,
       54,    0,   37,   37,    0,    0,    0,   49,    0,   48,
       23,   24,    0,   27,    0,    0,    0,    0,    0,   48,
       35,    0,   16,   18,    0,    0,    0,   16,   35,   18,
       50,   51,   50,   50,   35,   31,    0,   17,   19,    0,
        0,    0,    0,   13,    0,    0,    0,    0,   48,   13,
       50,   14,   14,   14,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    1,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   25,   25,   26,   27,
       28,   25,   25,   25,   25,   29,   30,   25,   25,   25,
       25,   31,   32,   33,   34,   35,   36,   37,   25,   25,
       38,   39,   40,   41,   25,    1,   24,   25,   25,   25,

       42,   43,   25,   25,   44,   25,   25,   29,   25,   45,
       46,   25,   25,   47,   32,   48,   49,   25,   25,   50,
       25,   25,   51,   52,   53,   54,    1,    1,    1,    1,
        1,   55,   56,   57,   58,   59,    1,   60,   61,    1,
        1,    1,    1,    1,    1,   62,    1,   63,   64,   65,
       66,    1,   67,    1,    1,   68,    1,    1,   69,    1,
       70,   71,    1,   72,    1,   73,   74,   75,   76,   77,
        1,   78,    1,    1,   79,    1,    1,    1,    1,    1,
        1,   80,    1,    1,   81,    1,   82,    1,    1,    1,
        1,    1,    1,   83,    1,    1,    1,    1,    1,    1,

        1,    1,    1,   84,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   85,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[86] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    1,
        1,    1,    1,    3,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    4,    4,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[209] =
    {   0,
        0,    0,   72,    0,   85,  121,   87,  108,  125,  160,
      207,    0,  449,  450,   89,  110,  450,  443,  440,  437,
      450,  450,  450,  112,    0,  406,  450,  450,  450,  450,
      123,  131,  133,  116,    0,    0,  121,    0,    0,  164,
      145,  429,  450,  419,  396,  450,  162,  184,  363,  115,
      201,    0,  416,  450,  450,  450,  152,  450,  450,  450,
      415,  392,    0,  187,  189,  450,  450,    0,  191,  193,
      450,  199,  450,  450,  423,  189,  450,  391,  389,  429,
        0,    0,  195,  428,  450,  450,  450,  409,  450,    0,
      200,  408,  198,  450,  450,  450,    0,  401,  214,  389,

      388,  202,  450,  204,  159,  450,  398,  379,  206,  402,
      207,  278,  450,  450,  212,  183,  216,  360,  368,  352,
      226,  350,  191,  362,  351,  267,  269,  272,  283,    0,
      275,    0,  310,  312,  450,  450,  305,  355,  368,  450,
        0,  349,  450,  450,  275,  347,  267,    0,  336,  260,
      450,  450,  344,  450,  294,  342,  269,  301,  274,  287,
        0,  246,  450,  450,  165,  162,  248,  450,  450,  450,
      304,    0,  307,  315,  318,  450,  199,  450,  450,  156,
      102,  259,  311,    0,  137,   91,   64,  270,  322,  329,
      332,  450,    0,  334,  450,  374,  379,  384,  389,  392,

       92,  396,  401,  405,  408,  410,  412,  414
    } ;

static yyconst flex_int16_t yy_def[209] =
    {   0,
      195,    1,    1,    3,  196,  196,  197,  197,  198,  198,
      198,   11,  195,  195,  195,  195,  195,  199,  195,  195,
      195,  195,  195,  195,  200,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  200,  200,  200,  200,  200,  195,
      195,  195,  195,  200,  200,  195,  195,  195,  195,  195,
      195,  201,  195,  195,  195,  195,  201,  195,  195,  195,
      201,  201,  202,  202,  202,  195,  195,  203,  203,  203,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  204,
      205,  205,  195,  199,  195,  195,  195,  195,  195,  200,
      195,  195,  195,  195,  195,  195,  206,  195,  200,  195,

      195,  195,  195,  195,  195,  195,  200,  200,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  207,  207,  207,  207,  202,
      202,  203,  203,  195,  195,  195,  195,  195,  204,  195,
      205,  195,  195,  195,  195,  195,  195,  206,  195,  200,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  200,
      200,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      207,  208,  207,  207,  207,  195,  195,  195,  195,  195,
      195,  195,  195,  200,  195,  195,  195,  195,  200,  207,
      207,  195,  200,  207,    0,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195
    } ;

static yyconst flex_int16_t yy_nxt[536] =
    {   0,
       14,   15,   16,   17,   18,   14,   19,   20,   21,   22,
       23,   14,   24,   25,   26,   27,   28,   14,   29,   30,
       31,   32,   14,   25,   25,   25,   33,   34,   25,   35,
       36,   25,   37,   38,   36,   39,   40,   41,   42,   14,
       43,   25,   44,   25,   25,   25,   25,   37,   25,   45,
       46,   47,   48,   17,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   49,   50,   51,   52,   64,   65,   69,   70,
       83,   83,   66,   67,  126,   52,   52,   52,   53,   54,

       52,   55,   56,   52,   57,   58,   56,   59,   60,   69,
       70,   83,   83,   52,   61,   52,   52,   52,   52,   57,
       52,   62,   64,   65,   88,  170,   15,   16,   66,   67,
       73,   97,   97,   97,   89,   91,   74,   71,   75,   72,
       76,   76,   76,   74,   92,   93,   94,   95,   97,   97,
       97,   99,  168,   96,  100,  101,   98,  102,   71,  168,
       72,   15,   16,  179,   77,   73,  103,   99,   78,   94,
       94,   74,   79,   75,  109,   76,   76,   76,   74,   97,
       97,   97,  127,  110,  104,  112,  112,  113,  131,  131,
      131,  131,  133,  133,  133,  133,   83,   83,  127,   77,

      134,  134,  135,   78,  137,  137,  137,   79,   15,   16,
      145,   80,  142,  106,  153,  158,  155,  178,  162,  146,
       81,  178,  143,  164,  154,  156,  163,  159,  163,  105,
       81,   81,   81,   82,   82,   81,   82,   82,   81,   81,
       82,   82,   82,   82,   96,  144,  111,  150,   82,   82,
       82,   81,   81,   81,   82,   81,   81,  115,  116,  117,
      118,  119,  150,  165,  166,  120,  121,  122,  163,  123,
       89,   96,  124,   89,  143,  167,  131,  131,  125,  112,
      112,  113,  147,   93,  168,  184,   87,  177,  157,   86,
      106,   86,  106,  172,  172,  172,  172,  178,  172,  172,

      174,  184,  173,  172,   87,  172,  185,  104,  172,  172,
      172,  133,  133,  134,  134,  135,  168,  173,  189,  172,
      137,  137,  137,  180,  181,  186,  187,  163,  164,  175,
      172,  172,  190,  172,  172,  182,  192,  188,  178,  179,
      172,  172,  172,  172,  172,  172,  191,  193,  190,  168,
      170,  172,  192,  154,  172,  172,  172,  194,  172,  172,
      172,  172,  154,  193,  170,  172,  154,  183,  172,  179,
      172,  143,  140,  194,   63,   63,   63,   63,   63,   68,
       68,   68,   68,   68,   14,   14,   14,   14,   14,   84,
       84,   84,   84,   84,   90,   90,  130,  176,  130,  130,

      130,  132,  132,  132,  132,  139,  139,  139,  139,  139,
      141,  141,  148,  148,  171,  171,  172,  172,  104,  170,
       93,  104,   93,  169,  164,  161,  160,  152,  151,  149,
      144,   89,   85,  140,  136,  138,  136,  129,  128,   98,
      114,  108,  107,  106,   86,   87,   86,   85,  195,   13,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195
    } ;

static yyconst flex_int16_t yy_chk[536] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    5,    5,    7,    7,
       15,   15,    5,    5,  201,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    8,
        8,   16,   16,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    6,    6,   24,  187,    9,    9,    6,    6,
        9,   34,   34,   34,   24,   31,    9,    7,    9,    7,
        9,    9,    9,    9,   31,   31,   32,   32,   33,   33,
       33,   37,  186,   32,   41,   41,   33,   41,    8,  185,
        8,   10,   10,  181,    9,   10,   41,   37,    9,   50,
       50,   10,    9,   10,   47,   10,   10,   10,   10,   40,
       40,   40,   57,   47,   41,   48,   48,   48,   64,   64,
       65,   65,   69,   69,   70,   70,   83,   83,   57,   10,

       72,   72,   72,   10,   76,   76,   76,   10,   11,   11,
       93,   11,   91,   47,  102,  105,  104,  180,  109,   93,
       11,  177,   91,  166,  102,  104,  165,  105,  109,   41,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,  116,  116,   47,   99,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   51,   51,   51,
       51,   51,   99,  111,  111,   51,   51,   51,  162,   51,
      123,  123,   51,  115,  115,  111,  131,  131,   51,  112,
      112,  112,   93,  121,  115,  150,  121,  145,  104,  117,
      117,  117,  117,  126,  126,  127,  127,  145,  128,  128,

      128,  150,  127,  126,  121,  127,  155,  121,  128,  129,
      129,  133,  133,  134,  134,  134,  155,  127,  160,  129,
      137,  137,  137,  147,  147,  157,  157,  167,  167,  129,
      171,  171,  173,  173,  173,  147,  183,  157,  182,  182,
      171,  174,  174,  173,  175,  175,  174,  189,  173,  188,
      188,  174,  183,  159,  175,  190,  190,  191,  191,  191,
      194,  194,  158,  189,  156,  190,  153,  149,  191,  146,
      194,  142,  139,  191,  196,  196,  196,  196,  196,  197,
      197,  197,  197,  197,  198,  198,  198,  198,  198,  199,
      199,  199,  199,  199,  200,  200,  202,  138,  202,  202,

      202,  203,  203,  203,  203,  204,  204,  204,  204,  204,
      205,  205,  206,  206,  207,  207,  208,  208,  125,  124,
      122,  120,  119,  118,  110,  108,  107,  101,  100,   98,
       92,   88,   84,   80,   79,   78,   75,   62,   61,   53,
       49,   45,   44,   42,   26,   20,   19,   18,   13,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ltlyy_flex_debug;
int ltlyy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ltlyytext;
#line 1 "ltlscan.ll"
/* -*- coding: utf-8 -*-
** Copyright (C) 2010, 2011, 2012, 2013, 2014, Laboratoire de
** Recherche et Développement de l'Epita (LRDE).
** Copyright (C) 2003, 2004  Laboratoire d'Informatique de Paris 6 (LIP6),
** département Systèmes Répartis Coopératifs (SRC), Université Pierre
** et Marie Curie.
**
** This file is part of Spot, a model checking library.
**
** Spot is free software; you can redistribute it and/or modify it
** under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 3 of the License, or
** (at your option) any later version.
**
** Spot is distributed in the hope that it will be useful, but WITHOUT
** ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
** or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
** License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#line 29 "ltlscan.ll"
#include <cstdlib>
#include <string>

#include "ltlparse/parsedecl.hh"
#include "misc/escape.hh"

#define YY_USER_ACTION \
  yylloc->columns(ltlyyleng);

static int start_token = 0;
static int parent_level = 0;
static bool missing_parent = false;
static bool lenient_mode = false;

typedef ltlyy::parser::token token;






#line 715 "ltlscan.cc"

#define INITIAL 0
#define not_prop 1
#define in_par 2
#define in_bra 3
#define sqbracket 4
#define lbt 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ltlyylex_destroy (void );

int ltlyyget_debug (void );

void ltlyyset_debug (int debug_flag  );

YY_EXTRA_TYPE ltlyyget_extra (void );

void ltlyyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ltlyyget_in (void );

void ltlyyset_in  (FILE * in_str  );

FILE *ltlyyget_out (void );

void ltlyyset_out  (FILE * out_str  );

yy_size_t ltlyyget_leng (void );

char *ltlyyget_text (void );

int ltlyyget_lineno (void );

void ltlyyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ltlyywrap (void );
#else
extern int ltlyywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ltlyytext, ltlyyleng, 1, ltlyyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ltlyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ltlyyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ltlyyin))==0 && ferror(ltlyyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ltlyyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ltlyylex (void);

#define YY_DECL int ltlyylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ltlyytext and ltlyyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ltlyyin )
			ltlyyin = stdin;

		if ( ! ltlyyout )
			ltlyyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ltlyyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ltlyy_create_buffer(ltlyyin,YY_BUF_SIZE );
		}

		ltlyy_load_buffer_state( );
		}

	{
#line 64 "ltlscan.ll"



  if (start_token)
    {
      int t = start_token;
      start_token = 0;
      return t;
    }
  yylloc->step();



#line 958 "ltlscan.cc"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ltlyytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 196 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 195 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 "ltlscan.ll"
{
				  if (!lenient_mode)
                                    {
				      BEGIN(0);
				      return token::PAR_OPEN;
                                    }
                                  /* Parse any (...) block as a single block,
				     taking care of nested parentheses.  The
				     parser will then try to parse this block
				     recursively.  */
                                  BEGIN(in_par);
                                  parent_level = 1;
				  yylval->str = new std::string();
                                }
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 92 "ltlscan.ll"
{
				  ++parent_level;
				  yylval->str->append(ltlyytext, ltlyyleng);
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 96 "ltlscan.ll"
{
				  if (--parent_level)
				    {
                                      yylval->str->append(ltlyytext, ltlyyleng);
				    }
				  else
				    {
                                      BEGIN(not_prop);
				      spot::trim(*yylval->str);
				      return token::PAR_BLOCK;
				    }
				}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 108 "ltlscan.ll"
yylval->str->append(ltlyytext, ltlyyleng);
	YY_BREAK
case YY_STATE_EOF(in_par):
#line 109 "ltlscan.ll"
{
				  unput(')');
				  if (!missing_parent)
                                    error_list.push_back(
				      spot::ltl::parse_error(*yylloc,
 					"missing closing parenthese"));
				  missing_parent = true;
				}
	YY_BREAK

case 5:
YY_RULE_SETUP
#line 119 "ltlscan.ll"
{
				  if (!lenient_mode)
				  {
				     BEGIN(0);
			             return token::BRACE_OPEN;
                                  }
                                  /* Parse any {...} block as a single block,
				     taking care of nested parentheses.  The
				     parser will then try to parse this block
				     recursively.  */
                                  BEGIN(in_bra);
                                  parent_level = 1;
				  yylval->str = new std::string();
                                }
	YY_BREAK

case 6:
YY_RULE_SETUP
#line 134 "ltlscan.ll"
{
				  ++parent_level;
				  yylval->str->append(ltlyytext, ltlyyleng);
				}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 138 "ltlscan.ll"
{
				  if (--parent_level)
				    {
                                      yylval->str->append(ltlyytext, ltlyyleng);
				    }
				  else
				    {
                                      BEGIN(not_prop);
				      spot::trim(*yylval->str);
				      return token::BRA_BANG_BLOCK;
				    }
                                }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 150 "ltlscan.ll"
{
				  if (--parent_level)
				    {
                                      yylval->str->append(ltlyytext, ltlyyleng);
				    }
				  else
				    {
                                      BEGIN(not_prop);
				      spot::trim(*yylval->str);
				      return token::BRA_BLOCK;
				    }
				}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 162 "ltlscan.ll"
yylval->str->append(ltlyytext, ltlyyleng);
	YY_BREAK
case YY_STATE_EOF(in_bra):
#line 163 "ltlscan.ll"
{
				  unput(')');
				  if (!missing_parent)
                                    error_list.push_back(
				      spot::ltl::parse_error(*yylloc,
 					"missing closing brace"));
				  missing_parent = true;
				}
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 173 "ltlscan.ll"
BEGIN(not_prop); return token::PAR_CLOSE;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 174 "ltlscan.ll"
BEGIN(not_prop); return token::BRACE_BANG_CLOSE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 175 "ltlscan.ll"
BEGIN(not_prop); return token::BRACE_CLOSE;
	YY_BREAK
/* Must go before the other operators, because the F of FALSE
     should not be mistaken with a unary F. */
case 13:
YY_RULE_SETUP
#line 179 "ltlscan.ll"
BEGIN(0); return token::CONST_TRUE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 180 "ltlscan.ll"
BEGIN(0); return token::CONST_FALSE;
	YY_BREAK
/* ~ comes from Goal, ! from everybody else */
case 15:
YY_RULE_SETUP
#line 184 "ltlscan.ll"
BEGIN(0); return token::OP_NOT;
	YY_BREAK
/* PSL operators */
case 16:
YY_RULE_SETUP
#line 187 "ltlscan.ll"
BEGIN(0); return token::OP_UCONCAT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 188 "ltlscan.ll"
BEGIN(0); return token::OP_ECONCAT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 189 "ltlscan.ll"
BEGIN(0); return token::OP_UCONCAT_NONO;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 190 "ltlscan.ll"
BEGIN(0); return token::OP_ECONCAT_NONO;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 191 "ltlscan.ll"
BEGIN(0); return token::OP_CONCAT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 192 "ltlscan.ll"
BEGIN(0); return token::OP_FUSION;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 193 "ltlscan.ll"
BEGIN(0); return token::OP_STAR;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 194 "ltlscan.ll"
BEGIN(0); return token::OP_BSTAR;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 195 "ltlscan.ll"
BEGIN(0); return token::OP_PLUS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 196 "ltlscan.ll"
BEGIN(sqbracket); return token::OP_STAR_OPEN;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 197 "ltlscan.ll"
BEGIN(sqbracket); return token::OP_EQUAL_OPEN;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 198 "ltlscan.ll"
BEGIN(sqbracket); return token::OP_GOTO_OPEN;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 199 "ltlscan.ll"
BEGIN(0); return token::OP_SQBKT_CLOSE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 200 "ltlscan.ll"
{
				  errno = 0;
				  unsigned long n = strtoul(ltlyytext, 0, 10);
                                  yylval->num = n;
				  if (errno || yylval->num != n)
				    {
                                      error_list.push_back(
				        spot::ltl::parse_error(*yylloc,
					  "value too large ignored"));
				      // Skip this number and read next token
                                      yylloc->step();
                                    }
				  else
                                    {
                                      return token::OP_SQBKT_NUM;
                                    }
				}
	YY_BREAK
/* .. is from PSL and EDL
   : is from Verilog and PSL
   to is from VHDL
   , is from Perl */
case 30:
YY_RULE_SETUP
#line 221 "ltlscan.ll"
return token::OP_SQBKT_SEP;
	YY_BREAK
/* In SVA you use [=1:$] instead of [=1..].  We will also accept
     [=1..$] and [=1:].  The PSL LRM shows examples like [=1:inf]
     instead, so will accept this too.  */
case 31:
YY_RULE_SETUP
#line 226 "ltlscan.ll"
return token::OP_UNBOUNDED;
	YY_BREAK
/* & and | come from Spin.  && and || from LTL2BA.
     /\, \/, and xor are from LBTT.
     --> and <--> come from Goal.
     +,*,^ are from Wring. */
case 32:
YY_RULE_SETUP
#line 232 "ltlscan.ll"
BEGIN(0); return token::OP_OR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "ltlscan.ll"
BEGIN(0); return token::OP_AND;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 234 "ltlscan.ll"
BEGIN(0); return token::OP_SHORT_AND;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 235 "ltlscan.ll"
BEGIN(0); return token::OP_XOR;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 236 "ltlscan.ll"
BEGIN(0); return token::OP_IMPLIES;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 237 "ltlscan.ll"
BEGIN(0); return token::OP_EQUIV;
	YY_BREAK
/* <>, [], and () are used in Spin.  */
case 38:
YY_RULE_SETUP
#line 240 "ltlscan.ll"
BEGIN(0); return token::OP_F;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 241 "ltlscan.ll"
BEGIN(0); return token::OP_G;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 242 "ltlscan.ll"
BEGIN(0); return token::OP_U;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 243 "ltlscan.ll"
BEGIN(0); return token::OP_R;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 244 "ltlscan.ll"
BEGIN(0); return token::OP_X;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 245 "ltlscan.ll"
BEGIN(0); return token::OP_W;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 246 "ltlscan.ll"
BEGIN(0); return token::OP_M;
	YY_BREAK
/* The combining overline or macron (overbar) should normally
     occur only after a single letter, but we do not check that. */
case 45:
YY_RULE_SETUP
#line 250 "ltlscan.ll"
return token::OP_POST_NEG;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 251 "ltlscan.ll"
return token::OP_POST_POS;
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 253 "ltlscan.ll"
/* discard whitespace */ yylloc->step ();
	YY_BREAK
/* An Atomic proposition cannot start with the letter
     used by a unary operator (F,G,X), unless this
     letter is followed by a digit in which case we assume
     it's an ATOMIC_PROP (even though F0 could be seen as Ffalse, we
     don't, because Ffalse is never used in practice).
  */
case 48:
#line 262 "ltlscan.ll"
case 49:
#line 263 "ltlscan.ll"
/*
     However if we have just parsed an atomic proposition, then we are
     not expecting another atomic proposition, so we can be stricter
     and disallow propositions that start with M, U, R, V, and W.  If
     you wonder why we do this, consider the Wring formula `p=0Uq=1'.
     When p is parsed, we enter the not_prop start condition, we
     remain into this condition when `=0' is processed, and then
     because we are in this condition we will not consider `Uq' as an
     atomic proposition but as a `U' operator followed by a `q' atomic
     proposition.

     We also disable atomic proposition that may look like a combination
     of a binary operator followed by several unary operators.
     E.g. UFXp.   This way, `p=0UFXp=1' will be parsed as `(p=0)U(F(X(p=1)))'.
  */
case 50:
#line 279 "ltlscan.ll"
case 51:
YY_RULE_SETUP
#line 279 "ltlscan.ll"
{
			  yylval->str = new std::string(ltlyytext, ltlyyleng);
			  BEGIN(not_prop);
			  return token::ATOMIC_PROP;
			}
	YY_BREAK
/* Atomic propositions can also be enclosed in double quotes.  */
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 286 "ltlscan.ll"
{
			  yylval->str = new std::string(ltlyytext + 1,
							ltlyyleng - 2);
			  BEGIN(not_prop);
			  return token::ATOMIC_PROP;
			}
	YY_BREAK
/* these are operators */
case 53:
YY_RULE_SETUP
#line 294 "ltlscan.ll"
return *ltlyytext;
	YY_BREAK
/* in LBT's format, atomic proposition look like p0 or p3141592, but
     for compatibility with ltl2dstar we also accept any alphanumeric
     string that is not an operator. */
case 54:
YY_RULE_SETUP
#line 298 "ltlscan.ll"
{
			  yylval->str = new std::string(ltlyytext, ltlyyleng);
			  return token::ATOMIC_PROP;
			}
	YY_BREAK
/* Atomic propositions can also be enclosed in double quotes.  */
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 304 "ltlscan.ll"
{
			  yylval->str = new std::string(ltlyytext + 1,
							ltlyyleng - 2);
			  return token::ATOMIC_PROP;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 311 "ltlscan.ll"
return *ltlyytext;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(not_prop):
case YY_STATE_EOF(sqbracket):
case YY_STATE_EOF(lbt):
#line 313 "ltlscan.ll"
return token::END_OF_INPUT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 315 "ltlscan.ll"
ECHO;
	YY_BREAK
#line 1469 "ltlscan.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ltlyyin at a new source and called
			 * ltlyylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ltlyyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ltlyywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ltlyytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of ltlyylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ltlyyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ltlyyrestart(ltlyyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ltlyyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 196 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 196 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 195);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ltlyytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ltlyyrestart(ltlyyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ltlyywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ltlyytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ltlyyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ltlyyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ltlyy_create_buffer(ltlyyin,YY_BUF_SIZE );
	}

	ltlyy_init_buffer(YY_CURRENT_BUFFER,input_file );
	ltlyy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ltlyy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ltlyypop_buffer_state();
	 *		ltlyypush_buffer_state(new_buffer);
     */
	ltlyyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ltlyy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ltlyywrap()) processing, but the only time this flag
	 * is looked at is after ltlyywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ltlyy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ltlyyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ltlyy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ltlyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ltlyy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ltlyyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ltlyy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ltlyy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ltlyy_create_buffer()
 * 
 */
    void ltlyy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ltlyyfree((void *) b->yy_ch_buf  );

	ltlyyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ltlyyrestart() or at EOF.
 */
    static void ltlyy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ltlyy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ltlyy_init_buffer was _probably_
     * called from ltlyyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ltlyy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ltlyy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ltlyypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ltlyyensure_buffer_stack();

	/* This block is copied from ltlyy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ltlyy_switch_to_buffer. */
	ltlyy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ltlyypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ltlyy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ltlyy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ltlyyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ltlyyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ltlyyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ltlyyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ltlyyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ltlyy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ltlyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ltlyy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ltlyy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ltlyylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ltlyy_scan_bytes() instead.
 */
YY_BUFFER_STATE ltlyy_scan_string (yyconst char * yystr )
{
    
	return ltlyy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ltlyylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ltlyy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ltlyyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ltlyy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ltlyy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ltlyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) ltlyyalloc(new_size  );

		else
			(yy_start_stack) = (int *) ltlyyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ltlyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ltlyytext[ltlyyleng] = (yy_hold_char); \
		(yy_c_buf_p) = ltlyytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ltlyyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ltlyyget_lineno  (void)
{
        
    return ltlyylineno;
}

/** Get the input stream.
 * 
 */
FILE *ltlyyget_in  (void)
{
        return ltlyyin;
}

/** Get the output stream.
 * 
 */
FILE *ltlyyget_out  (void)
{
        return ltlyyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t ltlyyget_leng  (void)
{
        return ltlyyleng;
}

/** Get the current token.
 * 
 */

char *ltlyyget_text  (void)
{
        return ltlyytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ltlyyset_lineno (int  line_number )
{
    
    ltlyylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ltlyy_switch_to_buffer
 */
void ltlyyset_in (FILE *  in_str )
{
        ltlyyin = in_str ;
}

void ltlyyset_out (FILE *  out_str )
{
        ltlyyout = out_str ;
}

int ltlyyget_debug  (void)
{
        return ltlyy_flex_debug;
}

void ltlyyset_debug (int  bdebug )
{
        ltlyy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ltlyylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    ltlyyin = stdin;
    ltlyyout = stdout;
#else
    ltlyyin = (FILE *) 0;
    ltlyyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ltlyylex_init()
     */
    return 0;
}

/* ltlyylex_destroy is for both reentrant and non-reentrant scanners. */
int ltlyylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ltlyy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ltlyypop_buffer_state();
	}

	/* Destroy the stack itself. */
	ltlyyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        ltlyyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ltlyylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ltlyyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ltlyyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ltlyyfree (void * ptr )
{
	free( (char *) ptr );	/* see ltlyyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 314 "ltlscan.ll"



void
flex_set_buffer(const std::string& buf,
		int start_tok, bool lenient)
{
  ltlyypush_buffer_state(YY_CURRENT_BUFFER);
  (void) ltlyy_scan_bytes(buf.c_str(),buf.size());
  start_token = start_tok;
  if (start_tok == token::START_LBT)
    yy_push_state(lbt);
  else
    yy_push_state(0);
  lenient_mode = lenient;
}

void
flex_unset_buffer()
{
  (void)&yy_top_state; // shut up a g++ warning.
  yy_pop_state();
  ltlyypop_buffer_state();
  missing_parent = false;
}

