#!/bin/sh

for i in 3 4 5 6 8; do
  dst=models/WCSasym$i.rg

  echo
  echo "MODELS += $dst/stamp"
  echo "$dst/stamp: $name/WCSasym$i.def $name/WCSasym$i.net $name/WCSasym$i.tobs"
  echo "	mkdir -p $dst"
  for e in def net tobs; do
    echo "	cp '\$(srcdir)/$name/WCSasym$i.$e' '$dst/WCSasym$i.rg.$e'"
    S="$S $name/WCSasym$i.$e"
  done
  echo "	echo 'P1 P2 P3 P4 P5 P6 P7 P8' > $dst/WCSasym$i.rg.ap"
  echo '	touch $@'
done
echo
echo "TEMPLATES +=$S $name/gen"
