/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory */

#ifndef _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory
#define _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory
 * Method:    read
 * Signature: ([BJI)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory_read
  (JNIEnv *, jobject, jbyteArray, jlong, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory
 * Method:    write
 * Signature: ([BJI)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory_write
  (JNIEnv *, jobject, jbyteArray, jlong, jint);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory
 * Method:    setup
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Cuda2DeviceMemory_setup
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
